### ISSUE TITLE
Handle missing mail_pw gracefully

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#106]
When logging in for the first time `mail_pw` is required and currently throws:

```
$ npm run dev

> deltachat-desktop@1.2.2 dev /home/lms/src/deltachat/deltachat-desktop
> npm run build && electron . --debug --disable-http-cache


> deltachat-desktop@1.2.2 build /home/lms/src/deltachat/deltachat-desktop
> buble src --output es5

(node:27205) Warning: N-API is an experimental feature and could change at any time.
init: 1508.588ms
/home/lms/src/deltachat/deltachat-desktop/node_modules/deltachat-node/index.js:100
      throw new Error('Missing .mail_pw')
            ^

Error: Missing .mail_pw
    at DeltaChat.configure (/home/lms/src/deltachat/deltachat-desktop/node_modules/deltachat-node/index.js:100:13)
    at /home/lms/src/deltachat/deltachat-desktop/es5/main/deltachat.js:110:10
    at binding.dcn_open.err (/home/lms/src/deltachat/deltachat-desktop/node_modules/deltachat-node/index.js:442:9)
```

We should handle this gracefully. Either by preventing an empty password to be filled in and/or by taking care of the thrown error and show error to user.

**Comment by ralphtheninja** [comment]
I think the best way is to disable the login button if addr or mail_pw fields are empty.
