### ISSUE TITLE
missing libssl

### ISSUE THREAD

**Issue by gerroon** [deltachat/deltachat-desktop#110]
Hi

I am trying to iuse it on Debian testing, I tried both the appimagea and the .deb, both complaints about missing  libssl.so.1.0.0: 

A JavaScript error occurred in the main process
Uncaught Exception:
Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at load (/tmp/.mount_deltacPxA4uR/resources/app.asar/node_modules/node-gyp-build/index.js:13:10)

thanks

**Comment by ralphtheninja** [comment]
@gerroon Thanks for input! Tried installing `libssl1.0.0`?

**Comment by ralphtheninja** [comment]
@gerroon Could you try this release? https://github.com/deltachat/deltachat-desktop/releases/tag/v1.2.3-bundled-openssl

**Comment by gerroon** [comment]
yeah it works (the ui opens0 with the bundled openssl. I cant test the account stuff though since my server requires manual settings.

**Comment by gerroon** [comment]
Still an issue in ./deltachat-desktop-1.3.0-x86_64.AppImage

A JavaScript error occurred in the main process
Uncaught Exception:
Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at load (/tmp/.mount_deltacN7yBtA/resources/app.asar/node_modules/node-gyp-build/index.js:13:10)
    at Object.<anonymous> (/tmp/.mount_deltacN7yBtA/resources/app.asar/node_modules/deltachat-node/binding.js:1:198)

**Comment by ralphtheninja** [comment]
Yes. But currently not going to do anything about it. Will re-open issue though.

**Comment by gerroon** [comment]
As of now the releases cant be run on Debian Sid. I propose Snap or Flatpak releases if it will solve the ssl issue.

**Comment by ralphtheninja** [comment]
@gerroon Could you please try out version 1.7.3 and see if this solves the issues with missing libssl on debian?

**Comment by flub** [comment]
What version of SSL does electron link against?  I think you should try
to link against that one.  Is that 1.1?

**Comment by ralphtheninja** [comment]
> What version of SSL does electron link against?

I have no idea. If I use `ldd` I get:

```
$ ldd node_modules/electron/dist/electron
	linux-vdso.so.1 (0x00007ffd621c9000)
	libnode.so => /home/lms/src/deltachat/deltachat-desktop/node_modules/electron/dist/libnode.so (0x00007f94f07dd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f94f05be000)
	libgtk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007f94efcb7000)
	libgdk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007f94ef9c1000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f94ef7b4000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f94ef567000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f94ef341000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f94ef024000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f94eee00000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f94eea61000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f94ee80d000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f94ee5c0000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f94ee3be000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f94ee196000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f94edf86000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f94edd7c000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f94edb79000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f94ed96e000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f94ed76b000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f94ed559000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f94ed353000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f94ed149000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f94ece11000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f94ecc0b000)
	libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1 (0x00007f94eca07000)
	libgconf-2.so.4 => /usr/lib/x86_64-linux-gnu/libgconf-2.so.4 (0x00007f94ec7d8000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f94ec5d4000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f94ec2be000)
	libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007f94ebf7a000)
	libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007f94ebd4b000)
	libsmime3.so => /usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007f94ebb1f000)
	libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007f94eb8e2000)
	libffmpeg.so => /home/lms/src/deltachat/deltachat-desktop/node_modules/electron/dist/libffmpeg.so (0x00007f94eb47c000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f94eb176000)
	libcups.so.2 => /usr/lib/x86_64-linux-gnu/libcups.so.2 (0x00007f94eaeea000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f94eace2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f94eaade000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f94ea899000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f94ea667000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f94ea2de000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f94e9f40000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f94e9d28000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f94e9937000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f94f1ab3000)
	libcairo-gobject.so.2 => /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007f94e972e000)
	libatk-bridge-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007f94e94fd000)
	libepoxy.so.0 => /usr/lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007f94e91fc000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f94e8fe6000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f94e8de3000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f94e8ba4000)
	libwayland-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007f94e899c000)
	libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f94e879a000)
	libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f94e858b000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f94e82d7000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f94e80ce000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f94e7e29000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f94e7bf7000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f94e79f4000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f94e77e7000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f94e75ca000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f94e73a2000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f94e7187000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f94e6f33000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f94e6d2b000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f94e6aa7000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f94e68a3000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f94e669d000)
	libdbus-glib-1.so.2 => /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2 (0x00007f94e6476000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f94e6204000)
	libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007f94e5fff000)
	libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007f94e5dfb000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f94e5bb0000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f94e584b000)
	libavahi-common.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007f94e563f000)
	libavahi-client.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007f94e542e000)
	libatspi.so.0 => /usr/lib/x86_64-linux-gnu/libatspi.so.0 (0x00007f94e51fe000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f94e4f60000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f94e4d59000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f94e4b0c000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f94e48e6000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f94e46ca000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f94e43af000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f94e419a000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f94e3ec4000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f94e3c92000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f94e3a8e000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f94e3883000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f94e3554000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f94e3337000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f94e2fb9000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f94e2da6000)
	libnettle.so.6 => /usr/local/lib/libnettle.so.6 (0x00007f94e2b6f000)
	libhogweed.so.4 => /usr/local/lib/libhogweed.so.4 (0x00007f94e2939000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f94e26b8000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f94e248b000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f94e2284000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f94e206f000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f94e1e6b000)
```

And there's no `libssl` in there. I can see that it links with `libnode.so` and if I check this I get:

```
$ ldd node_modules/electron/dist/electron/libnode.so
	linux-vdso.so.1 (0x00007ffc69baa000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3412623000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f341241f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3412217000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3411e8e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3411c76000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3411a57000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3411666000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3413c97000)
```

So I'm guessing this means that libssl is linked statically? Either inside `libnode.so` directly or in `electron`. Not sure how I can progress further here. They are completely stripped of symbols so `nm` doesn't give anything.

**Comment by gerroon** [comment]
Btw I use riot on the same device and I have no issue with ssl, maybe it helps

**Comment by ralphtheninja** [comment]
@gerroon So lets try this again. I've now created another build (from another server). Mind trying this out?

https://github.com/deltachat/deltachat-desktop/releases/tag/v1.7.5-test-custom-build

**Comment by gerroon** [comment]
i

Ok This works, I think because I am not seeing any of my chats from the Android app.

**Comment by ralphtheninja** [comment]
> Ok This works, I think because I am not seeing any of my chats from the Android app.

This is to be expected. Main thing is that you can run the application. Good to know! And thank you for reporting and helping out with testing!

**Comment by gerroon** [comment]
Cool. Will we able to grab the existing chats from the server?

**Comment by gerroon** [comment]
Sure but they are also stored on the server inside the chats folder? Cant it import from there?

**Comment by kasbah** [comment]
Hey, I still have this Issue on Ubuntu 16.04 with the stable appimage, deb and with the v1.7.5-test-custom-build appimage and deb. 

(Curious about the sync too but that's another issue. By the way found out about delta.chat through the [Autocrypt lighting talk at FOSDEM](https://fosdem.org/2019/schedule/event/autocrypt_email/).)
