### ISSUE TITLE
Arch Linux AUR deltachat-desktop-git crash on first run creating new account

### ISSUE THREAD

**Issue by emulti** [deltachat/deltachat-desktop#1288]
- Platform (linux/mac/windows): Arch Linux updated as of 12/31/19
- Delta Chat Desktop Version: 0.901.0.r12.g12878073-1
- Expected behavior: able to add and create login to new account
- Actual behavior: crash on startup
- Steps to reproduce the problem: install from AUR using makepkg -si, run and attempt to add first new account.
- Screenshots: NA
- Logs: see below

_Note: same credentials on Android app from G-Play create account normally._

Console log: 
$ deltachat 
Logfile: /home/chris/.config/DeltaChat/logs/2019-12-31-19-14-38.log.tsv
init: 2713.381ms
/opt/DeltaChat/electron_app/src/main/index.js:31
  throw err
  ^
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:208:11)
    at getNewAccountPath (/opt/DeltaChat/electron_app/src/main/logins.js:97:41)
    at EventEmitter.ipcMain.on (/opt/DeltaChat/electron_app/src/main/ipc.js:97:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/lib/electron4/resources/electron.asar/browser/api/web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)

Debug log attached (with .txt extension added)

[2019-12-31-19-17-51.log.tsv.txt](https://github.com/deltachat/deltachat-desktop/files/4013368/2019-12-31-19-17-51.log.tsv.txt)

**Comment by Jikstra** [comment]
Thanks for reporting :) Fixed it in a pr, sadly there's no easy way to build the AUR package from a specific branch or version. So you need to wait until this fix is getting merged or built the package a bit more manual.

**Comment by emulti** [comment]
Confirmed deltachat-desktop-git-0.901.0.r61.gb079c2e8-1-any.pkg.tar.xz built via AUR resolves the issue, thanks!
