### ISSUE TITLE
App doesn't start on Arch

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#1384]
```
App threw an error during load
Error: Cannot find module './tsc-dist/main'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/usr/lib/electron4/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/DeltaChat/electron_app/index.js:1:156)
    at Object.<anonymous> (/opt/DeltaChat/electron_app/index.js:3:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './tsc-dist/main'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/usr/lib/electron4/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/DeltaChat/electron_app/index.js:1:156)
    at Object.<anonymous> (/opt/DeltaChat/electron_app/index.js:3:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
```

**Comment by Simon-Laux** [comment]
Strange.. Did you run npm run build? Or do we have to specifically include the file somewhere?

Am 24. Januar 2020 01:24:07 MEZ schrieb Jikstra <notifications@github.com>:
>```
>App threw an error during load
>Error: Cannot find module './tsc-dist/main'
>    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
>at Function.Module._resolveFilename
>(/usr/lib/electron4/resources/electron.asar/common/reset-search-paths.js:43:12)
>    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
>    at Module.require (internal/modules/cjs/loader.js:640:17)
>    at require (internal/modules/cjs/helpers.js:20:18)
>    at Object.<anonymous> (/opt/DeltaChat/electron_app/index.js:1:156)
>    at Object.<anonymous> (/opt/DeltaChat/electron_app/index.js:3:3)
>    at Module._compile (internal/modules/cjs/loader.js:693:30)
>at Object.Module._extensions..js
>(internal/modules/cjs/loader.js:704:10)
>    at Module.load (internal/modules/cjs/loader.js:602:32)
>A JavaScript error occurred in the main process
>Uncaught Exception:
>Error: Cannot find module './tsc-dist/main'
>    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
>at Function.Module._resolveFilename
>(/usr/lib/electron4/resources/electron.asar/common/reset-search-paths.js:43:12)
>    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
>    at Module.require (internal/modules/cjs/loader.js:640:17)
>    at require (internal/modules/cjs/helpers.js:20:18)
>    at Object.<anonymous> (/opt/DeltaChat/electron_app/index.js:1:156)
>    at Object.<anonymous> (/opt/DeltaChat/electron_app/index.js:3:3)
>    at Module._compile (internal/modules/cjs/loader.js:693:30)
>at Object.Module._extensions..js
>(internal/modules/cjs/loader.js:704:10)
>    at Module.load (internal/modules/cjs/loader.js:602:32)
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-desktop/issues/1384

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Jikstra** [comment]
Recloned everything, now it works again. But it's weird as I did `git reset --hard HEAD` and stuff.. Also my aur package doesn't start with the same error and it's a clean build.

**Comment by Simon-Laux** [comment]
How do we proceed now? close this issue?

**Comment by Jikstra** [comment]
Currently rebuilding the aur package and lets see... I have a node v10 version set with nvm, probably that made problems?

**Comment by Simon-Laux** [comment]
> I have a node v10 version set with nvm, probably that made problems

unlikely that this forget to run the build command or excluded the directory

**Comment by Jikstra** [comment]
Nope still the same problem with a aur built. You're using arch too, can try out if it still builds a working version for you?

**Comment by Simon-Laux** [comment]
line 46 (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=deltachat-desktop-git#n46)
tsc-dist is missing and theoretically you can remove src
maybe also copy html-dist (parcel pr will use that folder) (but only do that if coping doesn't fail if the folder doesn't exist

**Comment by Simon-Laux** [comment]
in theory you only need the `tsc-dist/main` and `tsc-dist/shared` but as we might not use bundlers as much for the renderer in the future so I will not advocate for excluding it right ow.

**Comment by Jikstra** [comment]
Fixed it on AUR
