### ISSUE TITLE
Creating new chat from search bar is broken

### ISSUE THREAD

**Issue by pabzm** [deltachat/deltachat-desktop#1469]
If I enter an email address that I didn't chat with before into the search bar, I get the option to create a new chat with that address ("+ New contact").

Clicking on that button doesn't work (anymore). In the app, nothing happens, the log output shows this:

```
3499.9s [D]main/ipc: EVENT_DC_DISPATCH_CB (214) : contacts.createContact false,deltabot@example.net
3499.9s [E]main/deltachat: Error calling contacts.createContact(false, deltabot@example.net):
 TypeError: DeltaChat.maybeValidAddr is not a function
    at DCContacts.createContact (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/contacts.js:29:24)
    at DeltaChatController.<anonymous> (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:156:37)
    at Generator.next (<anonymous>)
    at /home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:3:12)
    at DeltaChatController.callMethod (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:143:16)
    at Object.<anonymous> (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/ipc.js:87:48)
    at Generator.next (<anonymous>)
    at /home/user/dev/dc/deltachat-desktop/tsc-dist/main/ipc.js:7:71 
DeltaChatController.<anonymous> (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:159:21),
/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:7:71,
__awaiter (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:3:12),
DeltaChatController.callMethod (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:143:16),
Object.<anonymous> (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/ipc.js:87:48)
3499.9s [D]main/ipc: EVENT_DC_DISPATCH_CB (215) : contacts.createChatByContactId 
3499.9s [w]main/deltachat/contacts: no contact could be found with id null 
DCContacts.createChatByContactId (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/contacts.js:38:17),
DeltaChatController.<anonymous> (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:156:37),
/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:7:71,
__awaiter (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:3:12),
DeltaChatController.callMethod (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/deltachat/controller.js:143:16),
Object.<anonymous> (/home/user/dev/dc/deltachat-desktop/tsc-dist/main/ipc.js:87:48)
3499.9s [D]main/ipc: EVENT_DC_DISPATCH_CB (216) : chatList.selectChat 0
3499.9s [D]main/deltachat/chatlist: Error: selected chat not found: 0
3499.9s [D]main/ipc: EVENT_DC_DISPATCH_CB (217) : messageList.getMessageIds 0
3499.9s [D]main/ipc: EVENT_DC_DISPATCH_CB (218) : messageList.getMessages 1,2,3,4,5,6,7,8,9
```

**Comment by r10s** [comment]
just tested, in 0.999.1-PREVIEW on mac (latest official release afaik) it was still ok.

**Comment by pabzm** [comment]
Confirming that it's fixed, thank you!
