### ISSUE TITLE
Crash when opening the settings (AUR)

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1716]
![2020-06-13_14-37](https://user-images.githubusercontent.com/18725968/84568965-62e95000-ad83-11ea-9407-efacc095ed5b.png)

```
TypeError: Cannot read property 'find' of null
    at shortCurrentValue (bundle.js:109244:35)
    at SettingsAppearance (bundle.js:109256:19)
    at renderWithHooks (bundle.js:20241:22)
    at updateFunctionComponent (bundle.js:22287:24)
    at beginWork$1 (bundle.js:24087:20)
    at HTMLUnknownElement.callCallback (bundle.js:4261:18)
    at Object.invokeGuardedCallbackDev (bundle.js:4310:20)
    at invokeGuardedCallback (bundle.js:4363:35)
    at beginWork$$1 (bundle.js:29692:11)
    at performUnitOfWork (bundle.js:28606:16)
```

Version: `master from aur`

**Comment by Simon-Laux** [comment]
looks like the themes folder is missing in the aur build.

**Comment by Jikstra** [comment]
Fixed: https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=deltachat-desktop-git&id=3fe492740b9534dc380e3bba27eeeca1b4bf4314
