### ISSUE TITLE
Unable to set a time for auto-deleting messages on Windows

### ISSUE THREAD

**Issue by whalehub** [deltachat/deltachat-desktop#1780]
- **Operating System (Linux/Mac/Windows/iOS/Android):** Windows
- **Delta Chat Version:** 1.4.3
- **Expected behavior:** After selecting a time for auto-deleting messages in the settings and clicking on the "Save" button, the selected time should be shown in the settings.
- **Actual behavior:** When I click on the "Save" button, nothing happens. The setting for auto-deleting messages continues to say "Off" and there's an error message in the logs.
- **Steps to reproduce the problem:**

1. Open DeltaChat.
2. Click on the three dots and select "Settings".
3. Scroll down to "Auto-delete messages".
4. Click on either of the two options and select a time.
5. Click "Save".
6. Click on "View" in the menu bar, hover over "Developer", then click on "Open current log file" to see the error message.

- **Screenshots:**

![DeltaChat](https://xbb.datahoarder.dev/VUSu3/BigATolI33.gif/raw)

- **Logs:** 

```
2020-07-08T16:05:23.511Z	main/deltachat        	ERROR	"\nDeltaChatController.<anonymous> (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:150:21),\nC:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:8:71,\n__awaiter (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:4:12),\nDeltaChatController.callMethod (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:133:16),\nObject.<anonymous> (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\ipc.js:73:52)"	"Error calling settings.estimateAutodeleteCount(false, 3600):\n TypeError: binding_1.default.dcn_estimate_deletion_cnt is not a function\n    at DeltaChat.estimateDeletionCount (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\dist\\deltachat.js:645:34)\n    at DCSettings.estimateAutodeleteCount (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\settings.js:141:25)\n    at DeltaChatController.<anonymous> (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:147:37)\n    at Generator.next (<anonymous>)\n    at C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:4:12)\n    at DeltaChatController.callMethod (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:133:16)\n    at Object.<anonymous> (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\ipc.js:73:52)\n    at Generator.next (<anonymous>)"
2020-07-08T16:05:26.385Z	main/deltachat        	ERROR	"\nDeltaChatController.<anonymous> (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:150:21),\nC:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:8:71,\n__awaiter (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:4:12),\nDeltaChatController.callMethod (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:133:16),\nObject.<anonymous> (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\ipc.js:73:52)"	"Error calling settings.estimateAutodeleteCount(true, 604800):\n TypeError: binding_1.default.dcn_estimate_deletion_cnt is not a function\n    at DeltaChat.estimateDeletionCount (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\dist\\deltachat.js:645:34)\n    at DCSettings.estimateAutodeleteCount (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\settings.js:141:25)\n    at DeltaChatController.<anonymous> (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:147:37)\n    at Generator.next (<anonymous>)\n    at C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:4:12)\n    at DeltaChatController.callMethod (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\deltachat\\controller.js:133:16)\n    at Object.<anonymous> (C:\\Users\\Aaron\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\tsc-dist\\main\\ipc.js:73:52)\n    at Generator.next (<anonymous>)"
```

**Comment by gerryfrancis** [comment]
I have tested with current version 1.4.3, and I can confirm this. Thanks for reporting, @whalehub !

**Comment by Simon-Laux** [comment]
looks like the windows prebuilds were outdated/broken the function is missing there, but this seems to only affect windows users.
