### ISSUE TITLE
Minified React error

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-desktop#1853]
- Operating System (Linux/Mac/Windows/iOS/Android):Desktop
- Delta Chat Version:1.4.3
- Steps to reproduce the problem: No idea, this has happened twice in three days now

Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.xi (bundle.js:12:59823)
    at useContext (bundle.js:4:4989)
    at u (bundle.js:30:973)
    at d (bundle.js:516:1469)
    at bundle.js:946:4791
    at d.value (bundle.js:814:3053)
    at so (bundle.js:12:71404)
    at co (bundle.js:12:71199)
    at Bo (bundle.js:12:106181)
    at Qu (bundle.js:12:90967)

The log seemed not to contain any useful info.

**Comment by Jikstra** [comment]
1.4.3 is old, can you use a new version pleeease? :D

**Comment by Simon-Laux** [comment]
it is probably https://github.com/deltachat/deltachat-desktop/issues/1803
