### ISSUE TITLE
Prompt "something crashed" when clicking the user avatar.

### ISSUE THREAD

**Issue by YamatoRyou** [deltachat/deltachat-desktop#2339]
- Operating System: x64 Windows 7
- Delta Chat Version: Version 1.20.3-DevBuild (git: v1.20.3-79-ge6bc7c5f-update_rocket_theme)
- Expected behavior: n/a
- Actual behavior: Prompt "something crashed" when clicking the user avatar
- Steps to reproduce the problem: n/a
- Screenshots:
![{E2E77DBB-30BA-0E27-CE73-63E88D76E120}](https://user-images.githubusercontent.com/48104960/129531518-3d991590-9c28-4de4-b2f3-632667c43521.png)
![{674F0CA6-D9F0-875D-80D7-829E6085C81D}](https://user-images.githubusercontent.com/48104960/129531583-6f9961e3-d2f8-4c7a-a32c-f6ad948821a2.png)
- Logs:
TypeError: Cannot read property 'split' of undefined  
    at FullscreenMedia (src/renderer/components/dialogs/FullscreenMedia.tsx:18:21)  
    at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)  
    at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17811:13)  
    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19049:16)  
    at HTMLUnknownElement.callCallback2 (node_modules/react-dom/cjs/react-dom.development.js:3945:14)  
    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)  
    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)  
    at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)  
    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)  
    at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)

**Comment by Jikstra** [comment]
Thanks, i can reproduce this

**Comment by Jikstra** [comment]
@Simon-Laux somehow we have a problem of file_mime being null quite often, more often then it used to be. Any ideas why?

**Comment by Simon-Laux** [comment]
because we now rely on the core doing it, so we should fix this in the core now probably

**Comment by Simon-Laux** [comment]
> Thanks, I can reproduce this

How?
