### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#2428]
```
react.development.js:220 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `About`. See https://reactjs.org/link/warning-keys for more information.
    at ClickableLink (file:///opt/DeltaChat/electron_app/html-dist/bundle.js:93597:23)
    at About (file:///opt/DeltaChat/electron_app/html-dist/bundle.js:103446:13)
    at div
    at div
    at DialogController (file:///opt/DeltaChat/electron_app/html-dist/bundle.js:105100:7)
    at div
    at ScreenController (file:///opt/DeltaChat/electron_app/html-dist/bundle.js:105232:7)
    at SettingsContextWrapper (file:///opt/DeltaChat/electron_app/html-dist/bundle.js:105553:37)
    at CrashScreen (file:///opt/DeltaChat/electron_app/html-dist/bundle.js:105448:7)
    at App (file:///opt/DeltaChat/electron_app/html-dist/bundle.js:105495:61)
 ```

**Comment by Simon-Laux** [comment]
related https://github.com/iansinnott/react-string-replace/issues/18
