### ISSUE TITLE
AUR package broken 

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#2889]
I don't know why but since we merged messagelist jsonrpc the aur package is broken for me. AppImage etc build from master work flawless, aur package not.

The problem is, if i want to select a chat, i get this error: 
```
ConnectivityToast.tsx:40 Uncaught TypeError: BackendRemote.rpc.maybeNetwork is not a function
    at ConnectivityToast.tsx:40:44
    at debounced (index.js:40:21)
(anonymous) @ ConnectivityToast.tsx:40
debounced @ index.js:40
ConnectivityToast.tsx:93 Uncaught (in promise) TypeError: BackendRemote.rpc.getConnectivity is not a function
    at ConnectivityToast.tsx:93:54
    at Generator.next (<anonymous>)
    at bundle.js:82:63
    at new Promise (<anonymous>)
    at __async (bundle.js:66:12)
    at ConnectivityToast.tsx:92:60
    at later (index.js:27:23)
(anonymous) @ ConnectivityToast.tsx:93
(anonymous) @ bundle.js:82
__async @ bundle.js:66
(anonymous) @ ConnectivityToast.tsx:92
later @ index.js:27
setTimeout (async)
debounced @ index.js:38
(anonymous) @ ChatListHelpers.tsx:22
wrapperCb @ ipc.ts:21
emit @ node:events:402
onMessage @ node:electron/js2c/renderer_init:69
Sidebar.tsx:227 Uncaught (in promise) TypeError: BackendRemote.rpc.getConnectivity is not a function
    at Sidebar.tsx:227:54
    at Generator.next (<anonymous>)
    at bundle.js:82:63
    at new Promise (<anonymous>)
    at __async (bundle.js:66:12)
    at Sidebar.tsx:226:60
    at later (index.js:27:23)
    ```

**Comment by Jikstra** [comment]
Fixed by [#d153766ea3e87b311a3625eb92e73048b5b84045](https://github.com/deltachat/deltachat-desktop/commit/d153766ea3e87b311a3625eb92e73048b5b84045)
