### ISSUE TITLE
Cannot read properties of undefined (reading 'toString') in Message.tsx:428:22

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3054]
```
TypeError: Cannot read properties of undefined (reading 'toString')
    at Component (file:///opt/DeltaChat/electron_app/src/renderer/components/message/Message.tsx:428:22)
    at renderWithHooks (file:///opt/DeltaChat/electron_app/node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (file:///opt/DeltaChat/electron_app/node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (file:///opt/DeltaChat/electron_app/node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (file:///opt/DeltaChat/electron_app/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (file:///opt/DeltaChat/electron_app/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (file:///opt/DeltaChat/electron_app/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at beginWork$1 (file:///opt/DeltaChat/electron_app/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
    at performUnitOfWork (file:///opt/DeltaChat/electron_app/node_modules/react-dom/cjs/react-dom.development.js:22779:12)
    at workLoopSync (file:///opt/DeltaChat/electron_app/node_modules/react-dom/cjs/react-dom.development.js:22707:5)
```

came up while fetching new messages, anyways this should not trigger a react crash view if possible.

**Comment by Simon-Laux** [comment]
Looks like the message id was `undefined`, the line in question is 
```
id={message.id.toString()}
```
we could probably ignore the error like this, but a message without a message id is invalid anyway. So the real issue is somewhere else.
```
id={String(message.id)}
```
```
id={message.id?.toString()}
```
