### ISSUE TITLE
crash out of nothing... related to network reset?

### ISSUE THREAD

**Issue by TheOtherDoctor** [deltachat/deltachat-desktop#3123]
- Operating System (Linux/Mac/Windows/iOS/Android): Linux Ubuntu 18.04.6 LTS
- Delta Chat: Version 1.34.0 (git: v1.33.0-65-gbcd36494)

- Expected behavior: don't crash.
- Actual behavior: crashes. ;-)

- Steps to reproduce the problem: 
unsure; happened, when I had to reset the defunct network uplink to a different (working) config while delta was running and probably was trying to send out a just-written message.

- Logs: Copied from popup:
TypeError: Cannot read properties of undefined (reading 'toString')
    at c (src/renderer/components/message/Message.tsx:428:22)
    at Ch (node_modules/react-dom/cjs/react-dom.production.min.js:157:137)
    at ck (node_modules/react-dom/cjs/react-dom.production.min.js:267:460)
    at bk (node_modules/react-dom/cjs/react-dom.production.min.js:250:347)
    at ak (node_modules/react-dom/cjs/react-dom.production.min.js:250:278)
    at Tj (node_modules/react-dom/cjs/react-dom.production.min.js:250:138)
    at c (node_modules/react-dom/cjs/react-dom.production.min.js:243:163)
    at b (node_modules/react-dom/cjs/react-dom.production.min.js:123:115)
    at Nf (node_modules/scheduler/cjs/scheduler.production.min.js:18:343)
    at xd (node_modules/react-dom/cjs/react-dom.production.min.js:122:325)

No idea if this is of any value. I did my best. ;-)

**Comment by Simon-Laux** [comment]
Probably some message failed to load, I'm working on a real fix in #3122, for now you can update to `1.34.4` and hope that that helps already a bit ;)
