### ISSUE TITLE
cannot start 1.36.0 on macos

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-desktop#3171]
getting the following error on macos :

<img width="600" alt="Screenshot 2023-04-09 at 12 54 54" src="https://user-images.githubusercontent.com/9800740/230768630-01d1f16c-f1b3-4d62-932a-5cd11f1f2f83.png">

this is the log mentioned in the error message:

```
2023-04-09T10:54:28.890Z	main/index            	INFO	""	"Deltachat Version 1.36.0 v1.33.0-181-ga1051f00 1680995063006"
2023-04-09T10:54:30.346Z	main/ipc              	CRITICAL	"\n/Applications/DeltaChat.app/Contents/Resources/app.asar/src/main/ipc.ts:34:9,\nObject.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/src/main/ipc.ts:46:3),\nModule._compile (node:internal/modules/cjs/loader:1141:14),\nObject.Module._extensions..js (node:internal/modules/cjs/loader:1196:10),\nModule.load (node:internal/modules/cjs/loader:1011:32),\nModule._load (node:internal/modules/cjs/loader:846:12),\nFunction.f._load (node:electron/js2c/asar_bundle:2:13330),\nModule.require (node:internal/modules/cjs/loader:1035:19)"	"Fatal: The DeltaChat Module couldn't be loaded. Please check if all dependencies for deltachat-core are installed!"	{"stack":"Error: Cannot find module 'ws'\nRequire stack:\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/isomorphic-ws/node.js\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/yerpc/dist/index.cjs\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/@deltachat/jsonrpc-client/dist/deltachat.cjs\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/ipc.js\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/index.js\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/index.js\n- \n    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)\n    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:109751)\n    at Module._load (node:internal/modules/cjs/loader:811:27)\n    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)\n    at Module.require (node:internal/modules/cjs/loader:1035:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/isomorphic-ws/node.js:3:18)\n    at Module._compile (node:internal/modules/cjs/loader:1141:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)\n    at Module.load (node:internal/modules/cjs/loader:1011:32)","message":"Cannot find module 'ws'\nRequire stack:\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/isomorphic-ws/node.js\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/yerpc/dist/index.cjs\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/@deltachat/jsonrpc-client/dist/deltachat.cjs\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/ipc.js\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/index.js\n- /Applications/DeltaChat.app/Contents/Resources/app.asar/index.js\n- ","code":"MODULE_NOT_FOUND","requireStack":["/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/isomorphic-ws/node.js","/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/yerpc/dist/index.cjs","/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/@deltachat/jsonrpc-client/dist/deltachat.cjs","/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/deltachat/controller.js","/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/ipc.js","/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/index.js","/Applications/DeltaChat.app/Contents/Resources/app.asar/index.js",null]}
2023-04-09T10:54:57.166Z	main/index            	INFO	""	"cwd /Users/bpetersen/Library/Application Support/DeltaChat/accounts"
2023-04-09T10:54:57.174Z	main/index            	CRITICAL	"\n/Applications/DeltaChat.app/Contents/Resources/app.asar/src/main/index.ts:107:9"	"Fatal Error during init"	{"stack":"TypeError: DeltaChatController is not a constructor\n    at Object.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/src/main/ipc.ts:53:24)\n    at Generator.next (<anonymous>)\n    at /Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/ipc.js:31:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/ipc.js:27:12)\n    at Object.init (/Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/ipc.js:72:12)\n    at /Applications/DeltaChat.app/Contents/Resources/app.asar/src/main/index.ts:127:37\n    at Generator.next (<anonymous>)\n    at /Applications/DeltaChat.app/Contents/Resources/app.asar/tsc-dist/main/index.js:31:71\n    at new Promise (<anonymous>)","message":"DeltaChatController is not a constructor"}
```

.dmg installed from https://download.delta.chat/desktop/v1.36.0/

i double checked and re-downloaded and re-installed - same error. after downgrade to 1.34.5, things are working again (still smooth downgrades, that's great!)

**Comment by Simon-Laux** [comment]
let's see if my attempt at a hot fix works: https://github.com/deltachat/deltachat-desktop/commit/c7e9f7bad45369dd147c07bcb079027ec9691699

**Comment by Simon-Laux** [comment]
please reopen if it does not work with https://download.delta.chat/desktop/v1.36.1/

**Comment by r10s** [comment]
worʞs foɿ mɘ \o/
