### ISSUE TITLE
Open html email does not work

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3229]
looks like some kind of race inside of the code that talks with electron:
```
Error occurred in handler for 'openMessageHTML': TypeError: Cannot read properties of undefined (reading 'handle')
    at openHtmlEmailWindow (/opt/DeltaChat/electron_app/src/main/windows/html_email.ts:68:26)
    at Object.<anonymous> (/opt/DeltaChat/electron_app/src/main/ipc.ts:235:26)
    at Generator.next (<anonymous>)
    at /opt/DeltaChat/electron_app/tsc-dist/main/ipc.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/DeltaChat/electron_app/tsc-dist/main/ipc.js:27:12)
    at /opt/DeltaChat/electron_app/src/main/ipc.ts:234:9
    at node:electron/js2c/browser_init:189:579
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11327)
    at EventEmitter.emit (node:events:526:28)
```
does not happen on apple M!, but on linux x86_64

**Comment by Simon-Laux** [comment]
ah it was using an old electron version, using the right electron version fixed the problem

**Comment by r10s** [comment]
puhh 😅
