### ISSUE TITLE
TypeError: DeltaChatController is not a constructor in Ubuntu 18.04 (wrong glibc version 2.28)

### ISSUE THREAD

**Issue by mythsmith** [deltachat/deltachat-desktop#3378]
DeltaChat uses GLIBC_2.28 since somewhere between v1.0.0 and 1.26.0, breaking ubuntu 18.04 compatibility. Happens also for flathub releases. The download page should clearly specify it is no longer compatible with ubuntu 18 and any other distro using a GLIBC older than 2.28.

- Operating System (Linux/Mac/Windows/iOS/Android): Ubuntu 18.04
- Delta Chat Version: tried 1.38.1, 1.37.1, 1.36.4, 1.26.0
- Expected behavior: DeltaChat start up
- Actual behavior: Exits immediately with a dialog displaying the error in the ticket title
- Steps to reproduce the problem: Install on ubuntu 18.04, start it
- Screenshots: 

![image](https://github.com/deltachat/deltachat-desktop/assets/1889232/8b944c60-22c7-40dc-b4d0-cf9c610191a5)

- Logs: 
```
Logfile: /home/daniele/.config/DeltaChat/logs/2023-09-05-10-05-54.log
Fatal Error
The DeltaChat Module couldn't be loaded.
 Please check if all dependencies for deltachat-core are installed!
 The Log file is located in this folder: /home/daniele/.config/DeltaChat/logs

 /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/DeltaChat/resources/app.asar.unpacked/node_modules/deltachat-node/node/prebuilds/linux-x64/node.napi.node)
```

And that log file contains only:
```
2023-09-05T08:05:54.104Z        main/index              INFO    ""      "Deltachat Version 1.38.1 v1.33.0-253-g5ff6e1e3 1687778551867"
2023-09-05T08:05:54.386Z        main/ipc                CRITICAL        "\n/opt/DeltaChat/resources/app.asar/src/main/ipc.ts:33:9,\nObject.<anonymous> (/opt/DeltaChat/resources/app.asar/src/main/ipc.ts:45:3),\nModule._compile (node:internal/modules/cjs/loader:1141:14),\nObject.Module._extensions..js (node:internal/modules/cjs/loader:1196:10),\nModule.load (node:internal/modules/cjs/loader:1011:32),\nModule._load (node:internal/modules/cjs/loader:846:12),\nFunction.f._load (node:electron/js2c/asar_bundle:2:13330),\nModule.require (node:internal/modules/cjs/loader:1035:19)"       "Fatal: The DeltaChat Module couldn't be loaded. Please check if all dependencies for deltachat-core are installed!"    {"stack":"Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/DeltaChat/resources/app.asar.unpacked/node_modules/deltachat-node/node/prebuilds/linux-x64/node.napi.node)\n    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)\n    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1226:18)\n    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)\n    at Module.load (node:internal/modules/cjs/loader:1011:32)\n    at Module._load (node:internal/modules/cjs/loader:846:12)\n    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)\n    at Module.require (node:internal/modules/cjs/loader:1035:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at load (/opt/DeltaChat/resources/app.asar/node_modules/node-gyp-build/node-gyp-build.js:22:10)\n    at Object.<anonymous> (/opt/DeltaChat/resources/app.asar/node_modules/deltachat-node/node/lib/binding.ts:7:55)","message":"/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/DeltaChat/resources/app.asar.unpacked/node_modules/deltachat-node/node/prebuilds/linux-x64/node.napi.node)","code":"ERR_DLOPEN_FAILED"}
2023-09-05T08:05:54.452Z        main/deltachat/webxdc   WARNING "\n/opt/DeltaChat/resources/app.asar/src/main/deltachat/webxdc.ts:551:9,\nrejected (/opt/DeltaChat/resources/app.asar/tsc-dist/main/deltachat/webxdc.js:6:65)"     "webxdc cleanup failed" {"stack":"Error: ENOENT: no such file or directory, scandir '/home/daniele/.config/DeltaChat/Partitions'","message":"ENOENT: no such file or directory, scandir '/home/daniele/.config/DeltaChat/Partitions'","errno":-2,"code":"ENOENT","syscall":"scandir","path":"/home/daniele/.config/DeltaChat/Partitions"}
```

NOTE: the app suddenly stopped working. I removed all data files from both ~/.config and /opt but the error still remains. 
Since this seems a GLIBC version problem:

```
$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
```

**Comment by Simon-Laux** [comment]
2.28 is actually already downgraded https://github.com/deltachat/deltachat-core-rust/pull/4448, we likely won't go older than that.
But if you need it you can still self compile it against an older glibc version. If you need help with that we can answer your questions about it.

CC @link2xt

**Comment by Simon-Laux** [comment]
@mythsmith 1.40.3 should work again, could you test it? https://download.delta.chat/desktop/v1.40.3/
we will put it on the website soon.

**Comment by Simon-Laux** [comment]
should be solved now
