### ISSUE TITLE
electron exited with signal SIGTRAP

### ISSUE THREAD

**Issue by adzialocha** [deltachat/deltachat-desktop#3459]
- Operating System (Linux/Mac/Windows/iOS/Android): `Linux 6.5.9-arch2-1 x86_64 GNU/Linux`
- Delta Chat Version: `Deltachat Version 1.40.4 v1.33.0-433-g2ee34084 1698919631540`
- Expected behavior: Electron starting when running `npm run dev`
- Actual behavior: Error `electron exited with signal SIGTRAP`

Related to the discussion in https://github.com/deltachat/deltachat-desktop/pull/3381 I can't start electron when running `npm run dev` (after compiling the rust core manually and using NodeJS `18.14.0`).

The error I'm seeing is:

```
> deltachat-desktop@1.40.4 start
> electron . --devmode --disable-http-cache --translation-watch

Logfile: /home/adz/.config/DeltaChat/logs/2023-11-02-11-07-17.log
0s [i]main/index: Deltachat Version 1.40.4 v1.33.0-433-g2ee34084 1698919631540
/home/adz/dev/deltachat/deltachat-desktop/node_modules/electron/dist/electron exited with signal SIGTRAP
```

I've poked a bit in the `src/main/index.ts` codebase and realized it might be due to running critical processes already before electron signals its `onReady` event (got the hint from this issue here https://github.com/electron/electron/issues/38592).

Will write a bit more as soon as I've figured out which code parts cause this race condition.

**Comment by adzialocha** [comment]
Alright, removing `import './resume_from_sleep'` https://github.com/deltachat/deltachat-desktop/blob/master/src/main/index.ts#L317 fixes the issue (and I stuble over others, but I'm not sure yet if they're related).

**Comment by Mic92** [comment]
Looks like you figured out? Anyway here is the backtrace for completeness:

```
Starting program: /nix/store/7a78jpnjx4m1s8wzdc45ayi1rbf3pwyg-electron-unwrapped-26.4.0/libexec/electron/electron /nix/store/mpzkxg88hpdsxg69phlxah8vn1hpaswr-deltachat-desktop-1.40.4/lib/node_modules/deltachat-desktop
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libthread_db.so.1".
[New Thread 0x7fffe60d96c0 (LWP 258667)]
[Detaching after fork from child process 258668]
[Detaching after fork from child process 258669]
[Detaching after fork from child process 258670]
[New Thread 0x7fffe58d86c0 (LWP 258673)]
[New Thread 0x7fffe50d76c0 (LWP 258674)]
[New Thread 0x7fffe48d66c0 (LWP 258675)]
[New Thread 0x7fffe38d46c0 (LWP 258677)]
[New Thread 0x7fffe40d56c0 (LWP 258676)]
[New Thread 0x7fffe30d36c0 (LWP 258678)]
[New Thread 0x7fffe28d26c0 (LWP 258679)]
[New Thread 0x7fffe1fd46c0 (LWP 258680)]
[New Thread 0x7fffe17d36c0 (LWP 258681)]
[New Thread 0x7fffe0fd26c0 (LWP 258682)]
[New Thread 0x7fffe07d16c0 (LWP 258683)]
[New Thread 0x7fff5ffd06c0 (LWP 258684)]
Logfile: /home/joerg/.config/DeltaChat/logs/2023-11-02-14-30-01.log
[Detaching after fork from child process 258685]
[Detaching after fork from child process 258688]
[Detaching after fork from child process 258693]
[Detaching after fork from child process 258696]
[Detaching after fork from child process 258699]
[Detaching after fork from child process 258702]
[New Thread 0x7fff5ed186c0 (LWP 258705)]
[New Thread 0x7fff5e5176c0 (LWP 258706)]
[New Thread 0x7fff5dd166c0 (LWP 258707)]
[New Thread 0x7fff5d5156c0 (LWP 258708)]

Thread 1 "electron" received signal SIGTRAP, Trace/breakpoint trap.
0x000055555c1ad173 in bluez::BluezDBusThreadManager::Get() ()
(gdb) bt
#0  0x000055555c1ad173 in bluez::BluezDBusThreadManager::Get() ()
#1  0x0000555557a24991 in electron::PowerObserverLinux::PowerObserverLinux(base::PowerSuspendObserver*) ()
#2  0x00005555578d514f in electron::api::PowerMonitor::Create(v8::Isolate*) ()
#3  0x00005555578a4a91 in void gin_helper::Invoker<gin_helper::IndicesHolder<0ul>, gin_helper::Arguments*>::DispatchToCallback<v8::Local<v8::Promise> >(base::RepeatingCallback<v8::Local<v8::Promise> (gin_helper::Arguments*)>) ()
#4  0x00005555578ac1b7 in gin_helper::Dispatcher<v8::Local<v8::Promise> (v8::Isolate*)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) ()
#5  0x00005555574c1342 in Builtins_CallApiCallbackGeneric ()
#6  0x00007fffffff7628 in ?? ()
#7  0x00007fffffff7660 in ?? ()
#8  0x0000000000000000 in ?? ()
```
