### ISSUE TITLE
Renderer stops working and shows black screen after some time

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop#3592]
In the console I see
```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94617)
    at WebContents.send (node:electron/js2c/browser_init:2:79767)
    at Object.send (/home/user/src/deltachat/deltachat-desktop/src/main/windows/main.ts:172:24)
    at AccountManager.<anonymous> (/home/user/src/deltachat/deltachat-desktop/src/main/deltachat/controller.ts:99:18)
```

Menu is still displayed, I can click File->Settings to get more errors like this.

This I select Quit and it shutdowns cleanly:
```
523.8s [i]main/index: Starting app shutdown process
523.8s [D]main/index: mainWindow.window.on('close')
523.9s [i]main/state: Saving state to /home/user/.config/DeltaChat/config.json
524.4s [i]main/index: Quitting now. Bye.
```

This is on Linux with Wayland (river wayland compositor).

**Comment by Simon-Laux** [comment]
> With native wayland mode there are no issues so far.

in flatpak there is a display scaling issue where it gets blurry, I guess it also exists outside of flatpak but haven't tried personally: https://github.com/flathub/chat.delta.desktop/pull/124#issuecomment-1962575127

- `--enable-features=UseOzonePlatform` - this is the default in newer chromium / electron versions, so not needed anymore
- `--ozone-platform-hint=auto` - this might still make sense, there is a pr to make it a default on https://github.com/flathub/chat.delta.desktop/pull/124 (which I included in the 1.44 update pr: https://github.com/flathub/chat.delta.desktop/pull/125)

Also we updated electron recently, does this also happen on the newer versions?

**Comment by Simon-Laux** [comment]
let's reopen this when it happens again

**Comment by WofWca** [comment]
I just encountered this on Windows in dev mode. The app was in the background then I came back to a blank screen.

The error occurs here:

https://github.com/deltachat/deltachat-desktop/blob/a6b56833d4746bf5a643ec214085574a84cd4f09/packages/target-electron/src/windows/main.ts#L240

In Electron it's here

https://github.com/electron/electron/blob/3d76d3a469d6fb22f0b6e137e210c81ae9e739fa/shell/browser/api/electron_api_web_frame_main.cc#L205-L214

The menu of the window is interactive, but clicking things like "Settings" just causes this error to be printed again.
The dev tools are blank, saying something along the lines of "disconnected".

I see no log entries that seem related.

I have a feeling that this has to do with OOM.

**Comment by link2xt** [comment]
This also keeps happening on Linux due too OOM, dmesg then shows that "electron" process got killed and the window remains but is all grey.

**Comment by nicodh** [comment]
Reopening since it still happens (see https://github.com/deltachat/deltachat-desktop/issues/5883 ), although not sure if and what we can do about it
