### ISSUE TITLE
MacBook camera stays active if QR scanner is closed too quickly

### ISSUE THREAD

**Issue by andrewgdotcom** [deltachat/deltachat-desktop#3943]
If I open the "scan QR code" tab and immediately close it, the camera on my macbook activates and stays active until I quit the application.

- Operating System (Linux/Mac/Windows/iOS/Android): MacOS Ventura (ARM)
- Delta Chat Version: 1.44.1 (DMG)
- Expected behavior: Camera should not activate if QR scanner has been exited
- Actual behavior: Camera stays active until application exits
- Steps to reproduce the problem: Open the "scan QR code" tab and quickly close it before the camera has time to activate.
- Screenshots: none, the only indication is the LED
- Logs: 

```
2024-06-16T16:20:24.059Z	renderer              	ERROR	"\nfile:///Applications/DeltaChat.app/Contents/Resources/app.asar/src/renderer/App.tsx:112:10"	"Unhandled Error:"	{"stack":"TypeError: Cannot read properties of null (reading 'srcObject')\n    at t.value (file:///Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/@deltachat/react-qr-reader/lib/index.js:215:19)","message":"Cannot read properties of null (reading 'srcObject')"}
2024-06-16T16:20:24.271Z	renderer              	ERROR	"\nfile:///Applications/DeltaChat.app/Contents/Resources/app.asar/src/renderer/App.tsx:112:10"	"Unhandled Error:"	{"stack":"TypeError: Cannot read properties of null (reading 'srcObject')\n    at t.value (file:///Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/@deltachat/react-qr-reader/lib/index.js:215:19)","message":"Cannot read properties of null (reading 'srcObject')"}
2024-06-16T16:20:24.465Z	renderer              	ERROR	"\nfile:///Applications/DeltaChat.app/Contents/Resources/app.asar/src/renderer/App.tsx:112:10"	"Unhandled Error:"	{"stack":"TypeError: Cannot read properties of null (reading 'srcObject')\n    at t.value (file:///Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/@deltachat/react-qr-reader/lib/index.js:215:19)","message":"Cannot read properties of null (reading 'srcObject')"}
2024-06-16T16:20:24.667Z	renderer              	ERROR	"\nfile:///Applications/DeltaChat.app/Contents/Resources/app.asar/src/renderer/App.tsx:112:10"	"Unhandled Error:"	{"stack":"TypeError: Cannot read properties of null (reading 'srcObject')\n    at t.value (file:///Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/@deltachat/react-qr-reader/lib/index.js:215:19)","message":"Cannot read properties of null (reading 'srcObject')"}
2024-06-16T16:20:24.869Z	renderer              	ERROR	"\nfile:///Applications/DeltaChat.app/Contents/Resources/app.asar/src/renderer/App.tsx:112:10"	"Unhandled Error:"	{"stack":"TypeError: Cannot read properties of null (reading 'srcObject')\n    at t.value (file:///Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/@deltachat/react-qr-reader/lib/index.js:215:19)","message":"Cannot read properties of null (reading 'srcObject')"}
```

**Comment by Simon-Laux** [comment]
we should have fixed this in 1.46, please try again with 1.46 (should be now also released on the download website).
If it persists, tell us and we'll reopen the issue.
