### ISSUE TITLE
React crash/error in message list: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3945]
```
Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ch (node_modules/react-dom/cjs/react-dom.production.min.js:157:334)
    at li (node_modules/react-dom/cjs/react-dom.production.min.js:180:154)
    at ck (node_modules/react-dom/cjs/react-dom.production.min.js:269:343)
    at bk (node_modules/react-dom/cjs/react-dom.production.min.js:250:347)
    at ak (node_modules/react-dom/cjs/react-dom.production.min.js:250:278)
    at Tj (node_modules/react-dom/cjs/react-dom.production.min.js:250:138)
    at c (node_modules/react-dom/cjs/react-dom.production.min.js:243:163)
    at b (node_modules/react-dom/cjs/react-dom.production.min.js:123:115)
    at Nf (node_modules/scheduler/cjs/scheduler.production.min.js:18:343)
    at gr (node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
```

happened after I clicked on download on a download on demand message, I'll open desktop in dev mode to find out more.

the message I downloaded was a video message.

**Comment by Simon-Laux** [comment]
happened to @adbenitez in #3997 also with a video message.

issue can probably be found by reading code and checking if some component has an return statement before an hook, which is not allowed.

**Comment by Simon-Laux** [comment]
in dev mode I got this more helpful error
```
Warning: React has detected a change in the order of Hooks called by Message2. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useContext                 useContext
3. useContext                 useContext
4. useContext                 useContext
5. useCallback                useCallback
6. useContext                 useContext
7. useContext                 useContext
8. useCallback                useCallback
9. useContext                 useContext
10. useCallback               useCallback
11. useCallback               useCallback
12. useCallback               useCallback
13. useCallback               useCallback
14. useContext                useContext
15. useContext                useContext
16. useCallback               useCallback
17. useContext                useContext
18. useContext                useContext
19. useCallback               useCallback
20. useContext                useContext
21. useCallback               useCallback
22. useContext                useContext
23. useCallback               useCallback
24. useContext                useContext
25. useContext                useContext
26. useContext                useContext
27. useCallback               useCallback
28. useContext                useContext
29. useContext                useContext
30. useCallback               useCallback
31. useCallback               useCallback
32. useContext                useContext
33. useCallback               useCallback
34. useCallback               useCallback
35. useCallback               useCallback
36. useCallback               useCallback
37. useContext                useContext
38. useCallback               useCallback
39. useCallback               useCallback
40. useCallback               useCallback
41. useState                  useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at Message2
```
