### ISSUE TITLE
crash when clicked download button in partial downloaded message

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-desktop#3997]
![image](https://github.com/deltachat/deltachat-desktop/assets/24558636/d6de6b5e-c30a-44d7-b78d-39e4b17b4f45)

the error in the screenshot:

```
Error: Minified React error [#300](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#); visit [https://reactjs.org/docs/error-decoder.html?invariant=300](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ch (nodemodules/react-dom/cjs/react-dom.production.min.js:157:334)
    at li (nodemodules/react-dom/cjs/react-dom.production.min.js:180:154)
    at ck (nodemodules/react-dom/cjs/react-dom.production.min.js:269:343)
    at bk (nodemodules/react-dom/cjs/react-dom.production.min.js:250:347)
    at ak (nodemodules/react-dom/cjs/react-dom.production.min.js:250:278)
    at Tj (nodemodules/react-dom/cjs/react-dom.production.min.js:250:138)
    at c (nodemodules/react-dom/cjs/react-dom.production.min.js:243:163)
    at b (nodemodules/react-dom/cjs/react-dom.production.min.js:123:115)
    at Nf (nodemodules/scheduler/cjs/scheduler.production.min.js:18:343)
    at gr (nodemodules/react-dom/cjs/react-dom.production.min.js:122:325)
```

In the log file:

```
2024-07-01T15:31:13.744Z	renderer/react-crashhandler	ERROR	"\nas.componentDidCatch ([file:///opt/DeltaChat/resources/app.asar/src/renderer/components/screens/RecoverableCrashScreen.tsx:24:9](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#)),\nas.o.componentDidCatch.n.callback ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:345](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#)),\nEg ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:131:408](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#)),\nYi ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:220:84](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#)),\nb ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:259:160](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#)),\nNf ([file:///opt/DeltaChat/resources/app.asar/node_modules/scheduler/cjs/scheduler.production.min.js:18:343](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#)),\ngg ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:122:325](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#)),\ndr ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:252:279](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))"	"The app encountered an react error"	{"stack":"Error: Minified React error [#300](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#); visit [https://reactjs.org/docs/error-decoder.html?invariant=300](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.\n    at Ch ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:157:334](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))\n    at li ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:180:154](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))\n    at ck ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:269:343](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))\n    at bk ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:347](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))\n    at ak ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:278](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))\n    at Tj ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:138](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))\n    at c ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:243:163](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))\n    at b ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:123:115](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))\n    at Nf ([file:///opt/DeltaChat/resources/app.asar/node_modules/scheduler/cjs/scheduler.production.min.js:18:343](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))\n    at gr ([file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:122:325](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#))","message":"Minified React error [#300](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#); visit [https://reactjs.org/docs/error-decoder.html?invariant=300](https://github.com/deltachat/deltachat-desktop/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#) for the full message or use the non-minified dev environment for full errors and additional helpful warnings."}
```

**Comment by Simon-Laux** [comment]
dupplicate of https://github.com/deltachat/deltachat-desktop/issues/3945
