### ISSUE TITLE
Installing AppImage fails on linux

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-desktop#40]
```
lms@x240 ~/Downloads
$ ./deltachat-desktop-1.0.3-x86_64.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './build/main'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/tmp/.mount_deltacYihPY2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_deltacYihPY2/resources/app.asar/index.js:1:156)
    at Object.<anonymous> (/tmp/.mount_deltacYihPY2/resources/app.asar/index.js:3:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```

**Comment by ralphtheninja** [comment]
Fixed in https://github.com/deltachat/deltachat-desktop/commit/d3fbc505e3b1a16729393bacb569d1ea8d5a1c29

**Comment by ralphtheninja** [comment]
So default configuration in `electron-builder` actually ignores the `build/` folder, which is exactly what it _shouldn't_ do ;)

**Comment by ralphtheninja** [comment]
So there's still something fishy. When I build locally with `npm run dist` and execute `./dist/deltachat-desktop-1.0.4-x86_64.AppImage` the app works, but it doesn't work if I download the built artifact. Grr.

**Comment by ralphtheninja** [comment]
@karissa Any idea?

**Comment by ralphtheninja** [comment]
So there were two problems. Second issue fixed in https://github.com/deltachat/deltachat-desktop/commit/ecadc262508e6e44ca4a2f9ebcaa373b0b1a16a4
