### ISSUE TITLE
Create group fails 

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#405]
- Platform (linux/mac/windows): ubuntu 16.04
- Delta Chat Desktop Version: master c9c356dc50061bae0fb710973aba088cd1dede0e
- Expected behavior: group created
- Actual behavior: traceback
- Steps to reproduce the problem: create a group, select a few people to be part of it, hit "new group" and get the below screenshot. 
- Screenshots:
- Logs:

```(node:25925) Warning: N-API is an experimental feature and could change at any time.
init: 2085.989ms
Error: napi_get_value_string_utf8(env, argv[2], NULL, 0, &image_size) failed!
    at DeltaChat.setChatProfileImage (/home/hpk/p/delta/desktop/node_modules/deltachat-node/index.js:527:15)
    at DeltaChatController._setGroupData (/home/hpk/p/delta/desktop/src/main/deltachat.js:295:14)
    at DeltaChatController.createUnverifiedGroup (/home/hpk/p/delta/desktop/src/main/deltachat.js:291:17)
    at dispatch (/home/hpk/p/delta/desktop/src/main/ipc.js:90:20)
    at EventEmitter.ipc.on.args (/home/hpk/p/delta/desktop/src/main/ipc.js:54:21)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/home/hpk/p/delta/desktop/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

**Comment by ralphtheninja** [comment]
Fixed in https://github.com/deltachat/deltachat-node/releases/tag/v0.28.1 , please reinstall dependencies: `rm -rf node_modules && npm i`
