### ISSUE TITLE
1.46.8: crashes after .deb upgrade from 1.42 on Ubuntu 24.10.

### ISSUE THREAD

**Issue by g6094199** [deltachat/deltachat-desktop#4262]
- Operating System (Linux/Mac/Windows/iOS/Android):  ubuntu 22.04/22.10
- Delta Chat Version: 1.46.8
- Expected behavior:
- Actual behavior:  only DS window is shown. no account content visible.
- Steps to reproduce the problem: upgrade from 1.42 to 1.46.8 via .deb
- Screenshots:
- Logs:
 
>2024-10-25T09:23:45.800Z	main/index            	INFO	""	"Deltachat Version 1.46.8 v1.33.0-989-g5018d9d4 1725889321252"
2024-10-25T09:23:46.128Z	main/index            	INFO	""	"cwd /home/masterb/.config/DeltaChat/accounts"
2024-10-25T09:23:46.134Z	main/deltachat        	INFO	""	"using deltachat-rpc-server at"	{"serverPath":"/opt/DeltaChat/resources/app.asar.unpacked/node_modules/@deltachat/stdio-rpc-server-linux-x64/deltachat-rpc-server"}
2024-10-25T09:23:46.140Z	main/deltachat        	INFO	""	"HI"
2024-10-25T09:23:46.141Z	main/deltachat        	INFO	""	"Ready, starting accounts io..."
2024-10-25T09:23:46.141Z	main/deltachat        	INFO	""	"Started accounts io."
2024-10-25T09:23:46.319Z	main/menu             	INFO	""	"rebuilding menu with locale de"
2024-10-25T09:23:46.348Z	logger/log-cleanup    	INFO	""	"Successfuly deleted 1 old logfiles"
2024-10-25T09:23:46.571Z	core/event            	INFO	""	1	"src/scheduler.rs:66: starting IO"
2024-10-25T09:23:46.661Z	/mainWindow           	INFO	""	"preq"	"background-sync"
2024-10-25T09:23:46.661Z	/mainWindow           	INFO	""	"main window requested \"background-sync\" permission, but we denied it, because it is not in the list of allowed permissions."
2024-10-25T09:23:46.727Z	main/menu             	INFO	""	"rebuilding menu with locale de"
2024-10-25T09:23:46.749Z	renderer/stockstrings 	INFO	""	"loading core translations"
2024-10-25T09:23:47.709Z	main/state            	INFO	""	"Saving state to /home/masterb/.config/DeltaChat/config.json"
2024-10-25T09:24:01.637Z	main/state            	INFO	""	"Saving state to /home/masterb/.config/DeltaChat/config.json"
2024-10-25T09:24:05.464Z	renderer/react-crashhandler	ERROR	"\nBc.componentDidCatch (file:///opt/DeltaChat/resources/app.asar/src/renderer/components/screens/CrashScreen.tsx:17:9),\nBc.T_.o.componentDidCatch.n.callback (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:345),\nEg (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:131:408),\nYi (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:220:84),\nb (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:259:160),\nNf (file:///opt/DeltaChat/resources/app.asar/node_modules/scheduler/cjs/scheduler.production.min.js:18:343),\ngg (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:122:325),\nEr (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:252:279)"	"The app encountered an react error"	{"stack":"Error: no context selected\n    at selectedAccountId (file:///opt/DeltaChat/resources/app.asar/src/renderer/ScreenController.tsx:372:11)\n    at c (file:///opt/DeltaChat/resources/app.asar/src/renderer/components/helpers/ClickableLink.tsx:13:21)\n    at Ch (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:157:137)\n    at ck (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:267:460)\n    at bk (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:347)\n    at ak (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:278)\n    at Tj (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:138)\n    at c (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:243:163)\n    at b (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:123:115)\n    at T1.unstable_runWithPriority (file:///opt/DeltaChat/resources/app.asar/node_modules/scheduler/cjs/scheduler.production.min.js:18:343)","message":"no context selected"}
2024-10-25T09:24:05.465Z	renderer/react-crashhandler	ERROR	"\nBc.componentDidCatch (file:///opt/DeltaChat/resources/app.asar/src/renderer/components/screens/CrashScreen.tsx:17:9),\nBc.T_.o.componentDidCatch.n.callback (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:345),\nEg (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:131:408),\nYi (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:220:84),\nb (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:259:160),\nNf (file:///opt/DeltaChat/resources/app.asar/node_modules/scheduler/cjs/scheduler.production.min.js:18:343),\ngg (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:122:325),\nEr (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:252:279)"	"The app encountered an react error"	{"stack":"Error: no context selected\n    at selectedAccountId (file:///opt/DeltaChat/resources/app.asar/src/renderer/ScreenController.tsx:372:11)\n    at c (file:///opt/DeltaChat/resources/app.asar/src/renderer/components/helpers/ClickableLink.tsx:13:21)\n    at Ch (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:157:137)\n    at ck (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:267:460)\n    at bk (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:347)\n    at ak (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:278)\n    at Tj (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:138)\n    at c (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:243:163)\n    at b (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:123:115)\n    at T1.unstable_runWithPriority (file:///opt/DeltaChat/resources/app.asar/node_modules/scheduler/cjs/scheduler.production.min.js:18:343)","message":"no context selected"}
2024-10-25T09:24:05.467Z	renderer/react-crashhandler	ERROR	"\nBc.componentDidCatch (file:///opt/DeltaChat/resources/app.asar/src/renderer/components/screens/CrashScreen.tsx:17:9),\nBc.T_.o.componentDidCatch.n.callback (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:345),\nEg (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:131:408),\nYi (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:220:84),\nb (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:259:160),\nNf (file:///opt/DeltaChat/resources/app.asar/node_modules/scheduler/cjs/scheduler.production.min.js:18:343),\ngg (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:122:325),\nEr (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:252:279)"	"The app encountered an react error"	{"stack":"Error: no context selected\n    at selectedAccountId (file:///opt/DeltaChat/resources/app.asar/src/renderer/ScreenController.tsx:372:11)\n    at c (file:///opt/DeltaChat/resources/app.asar/src/renderer/components/helpers/ClickableLink.tsx:13:21)\n    at Ch (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:157:137)\n    at ck (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:267:460)\n    at bk (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:347)\n    at ak (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:278)\n    at Tj (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:250:138)\n    at c (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:243:163)\n    at b (file:///opt/DeltaChat/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:123:115)\n    at T1.unstable_runWithPriority (file:///opt/DeltaChat/resources/app.asar/node_modules/scheduler/cjs/scheduler.production.min.js:18:343)","message":"no context selected"}`

**Comment by g6094199** [comment]
cant test on the reported machine right now. only on another ubuntu box and on this one it works.

**Comment by Simon-Laux** [comment]
I think you can fix it by removing the `"lastAccount"` key from your config.json. I think on linux it should be at `~/.config/DeltaChat/config.json`.

I suspect there is an invalid value in there.

I think it should not be an issue anymore, also unless we know more it is not really actionable at this point. The log points to that the selected account is not set, and that variable comes from the config file.

I'll close this now, let's reopen or create a new issue should this appear again with current versions. (versions >= 1.50.1)
