### ISSUE TITLE
napi_get_string error on exporting backup

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#444]
This happens everytime i'm trying to export a backup. Export seems to work, at least the progress bar is doing something. Didn't test the backup.

```
Error: napi_get_value_string_utf8(env, argv[3], NULL, 0, &param2_size) failed!
    at DeltaChat.importExport (/home/kerle/Workspace/deltachat-desktop/node_modules/deltachat-node/index.js:386:13)
    at DeltaChatController.backupExport (/home/kerle/Workspace/deltachat-desktop/src/main/deltachat.js:365:14)
    at dispatch (/home/kerle/Workspace/deltachat-desktop/src/main/ipc.js:114:20)
    at EventEmitter.ipc.on.args (/home/kerle/Workspace/deltachat-desktop/src/main/ipc.js:72:5)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:284:13)
    at WebContents.emit (events.js:182:13)
```

**Comment by ralphtheninja** [comment]
Can you check the values passed in from desktop to the node bindings? I suspect a `null` value or something is in there.

**Comment by karissa** [comment]
are you on the latest deltachat-node?

**Comment by ralphtheninja** [comment]
@karissa Aaah yes, we fixed this didn't we? :)

**Comment by ralphtheninja** [comment]
Hmm, nevermind, it was chat profile image.

**Comment by Jikstra** [comment]
I'm on the latest master and this happens to me. Doesn't this happen on your side if you're exporting a backup? The error is only shown in the terminal.

**Comment by ralphtheninja** [comment]
> I'm on the latest master and this happens to me. Doesn't this happen on your side if you're exporting a backup? The error is only shown in the terminal.

Please do some `console.log`-stuff so we can find out why this happens.

**Comment by Jikstra** [comment]
Problem seems to be that we're not passing `null` as param2 but `undefined` and that `undefined`/`null` isn't getting translated to `NULL` from `NAPI_ARGV_UTF8_MALLOC`. So this is a deltachat-node bug.

**Comment by Jikstra** [comment]
Fixed with: https://github.com/deltachat/deltachat-node/pull/209
