### ISSUE TITLE
Crash upon deleting profile

### ISSUE THREAD

**Issue by roughnecks** [deltachat/deltachat-desktop#4445]
- Operating System: Windows
- Delta Chat Version: Delta Chat Desktop | 1.50.1 (git: v1.33.0-1249-g3d79da0a-prepare-release-1.50.1)

I was removing a chatmail profile and after clicking on "delete" nothing seemed to happen, so I clicked again. DC crashed.
When restarting the app, in place of the avatar image (for the deleted account) on the left sidebar, there was a question mark.. After clicking on another account of mine, it went away.

- Logs:

```
Error: no context selected
    at selectedAccountId (src/ScreenController.tsx:386:11)
    at useThreeDotMenu (src/components/ThreeDotMenu.tsx:28:21)
    at Component (src/components/screens/MainScreen.tsx:137:31)
    at renderWithHooks (file:///D:/WindowsApps/merlinux.DeltaChat_1.50.1.0_x64__v2ry5hvxhdhyy/app/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (file:///D:/WindowsApps/merlinux.DeltaChat_1.50.1.0_x64__v2ry5hvxhdhyy/app/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (file:///D:/WindowsApps/merlinux.DeltaChat_1.50.1.0_x64__v2ry5hvxhdhyy/app/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (file:///D:/WindowsApps/merlinux.DeltaChat_1.50.1.0_x64__v2ry5hvxhdhyy/app/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (file:///D:/WindowsApps/merlinux.DeltaChat_1.50.1.0_x64__v2ry5hvxhdhyy/app/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (file:///D:/WindowsApps/merlinux.DeltaChat_1.50.1.0_x64__v2ry5hvxhdhyy/app/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at beginWork$1 (file:///D:/WindowsApps/merlinux.DeltaChat_1.50.1.0_x64__v2ry5hvxhdhyy/app/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
```

**Comment by roughnecks** [comment]
This morning, the question mark in place of the avatar is again there: https://sharer.woodpeckersnest.space/FuzE5/WOvISEgO31/raw.jpg

**Comment by WofWca** [comment]
I believe this is a duplicate of https://github.com/deltachat/deltachat-desktop/issues/3959.
