### ISSUE TITLE
Some references to log are wrong

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#555]
Due to the new logger i think, example for an error:
```
TypeError: log is not a function
    at DeltaChatController.setConfig (/home/kerle/Workspace/deltachat-desktop/src/main/deltachat.js:394:5)
    at dispatch (/home/kerle/Workspace/deltachat-desktop/src/main/ipc.js:171:20)
    at EventEmitter.ipc.on.args (/home/kerle/Workspace/deltachat-desktop/src/main/ipc.js:97:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/home/kerle/Workspace/deltachat-desktop/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:293:13)
    at WebContents.emit (events.js:182:13)
main/index uncaughtError uncaught_error { message: 'log is not a function',
  stack:
   'TypeError: log is not a function\n    at DeltaChatController.setConfig (/home/kerle/Workspace/deltachat-desktop/src/main/deltachat.js:394:5)\n    at dispatch (/home/kerle/Workspace/deltachat-desktop/src/main/ipc.js:171:20)\n    at EventEmitter.ipc.on.args (/home/kerle/Workspace/deltachat-desktop/src/main/ipc.js:97:21)\n    at EventEmitter.emit (events.js:182:13)\n    at WebContents.<anonymous> (/home/kerle/Workspace/deltachat-desktop/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:293:13)\n    at WebContents.emit (events.js:182:13)' } [ { columnNumber: 9,
    lineNumber: 74,
    fileName: '/home/kerle/Workspace/deltachat-desktop/src/main/index.js',
    functionName: 'process.on',
    source:
     '    at process.on (/home/kerle/Workspace/deltachat-desktop/src/main/index.js:74:9)' },
  { columnNumber: 15,
    lineNumber: 187,
    fileName: 'events.js',
    functionName: 'process.emit',
    source: '    at process.emit (events.js:187:15)' },
  { columnNumber: 27,
    lineNumber: 451,
    fileName: 'internal/bootstrap/node.js',
    functionName: 'process._fatalException',
    source:
     '    at process._fatalException (internal/bootstrap/node.js:451:27)' } ]
```

Reproducable by trying to change any of the imap folder settings

**Comment by Jikstra** [comment]
The bug mentioned here was fixed by https://github.com/deltachat/deltachat-desktop/pull/556

But not sure if other log references are wrong too? @Simon-Laux can we somehow figure this out?

**Comment by Simon-Laux** [comment]
we could do a grep ` log(`

**Comment by ralphtheninja** [comment]
It looks ok.
