### ISSUE TITLE
AppImage cannot find libsasl2.so (on OpenSUSE Leap 15)

### ISSUE THREAD

**Issue by Frando** [deltachat/deltachat-desktop#642]
- Platform (linux/mac/windows):

Linux, OpenSUSE Leap 15

- Delta Chat Desktop Version:

deltachat-desktop-0.100.0-x86_64.AppImage 

- Expected behavior:

Opening the AppImage launches DeltaChat

- Actual behavior:

We tried to open deltachat-desktop-0.100.0-x86_64.AppImage on a computer running OpenSUSE Leap 15. It failed with:

```bash
./deltachat-desktop-0.100.0-x86_64.AppImage 
Invalid MIT-MAGIC-COOKIE-1 keyLogfile: /home/jochen/.config/DeltaChat/logs/2019-01-29T21:35:44.921Z.log
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsasl2.so.2: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (/tmp/.mount_deltacoFYxJu/resources/app.asar/node_modules/node-gyp-build/index.js:16:10)
    at Object.<anonymous> (/tmp/.mount_deltacoFYxJu/resources/app.asar/node_modules/deltachat-node/binding.js:1:198)
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key

```

It says it cannot find ibsasl2.so.2. In yast, the package `libsasl2-3` is installed (version 2.1.26-lp150.3.7). The package says it installed 2 files:

```
/usr/lib64/libsasl2.so.3
/usr/lib64/libsasl2.so.3.0.0
```

- Steps to reproduce the problem:

See above

**Comment by ralphtheninja** [comment]
I'm going to close this since it's a duplicate.
