### ISSUE TITLE
Error: libsasl2.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by jmliz** [deltachat/deltachat-desktop#653]
- Platform (linux/mac/windows): Fedora Linux Workstation 29
- Delta Chat Desktop Version: deltachat-desktop-0.100.0-x86_64.AppImage
- Expected behavior: The app launches
- Actual behavior: It crashes with error code.
- Steps to reproduce the problem: download the appimage package give +x permissions and execute from terminal
- Screenshots: not provided
- Logs: below

```
[user@computer Downloads]$ ./deltachat-desktop-0.100.0-x86_64.AppImage 
Logfile: /home/user/.config/DeltaChat/logs/2019-01-31T19:00:35.287Z.log
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsasl2.so.2: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (/tmp/.mount_deltacPudjru/resources/app.asar/node_modules/node-gyp-build/index.js:16:10)
    at Object.<anonymous> (/tmp/.mount_deltacPudjru/resources/app.asar/node_modules/deltachat-node/binding.js:1:198)
```

I've already tried to solve it by installing python-devel openldap-devel cyrus-sasl as adviced at some forums but they were already installed and the error keeps showing and the app doesn't launch.

**Comment by Jikstra** [comment]
This is a known bug and happens because we currently can't include libsasl/cyrus-sasl into the deltachat-core library.
1. So you have to install cyrus-sasl (which you already have done) 
2. Make sure there's a libsasl2.so.2 in `/usr/include`. If there's not, you can try to do a softlink to your libsasl.so. I can help you with that if you give me the output of a `find /usr -name libsasl*`.

This a annoying thing, maybe it makes sense to build deltachat-desktop on some fedora at some point but there a dozens of distributions with different version of sasl.

**Comment by jmliz** [comment]
@Jikstra thanks. I'd appreciate some help. here's the output

```
/usr/lib64/libsasl2.so
/usr/lib64/libsasl2.so.3
/usr/lib64/sasl2/libsasldb.so.3.0.0
/usr/lib64/sasl2/libsasldb.so.3
/usr/lib64/sasl2/libsasldb.so
/usr/lib64/pkgconfig/libsasl2.pc
/usr/lib64/libsasl2.so.3.0.0
find: ‘/usr/libexec/initscripts/legacy-actions/auditd’: Permission denied
/usr/lib/libsasl2.so.3
/usr/lib/sasl2/libsasldb.so.3.0.0
/usr/lib/sasl2/libsasldb.so.3
/usr/lib/sasl2/libsasldb.so
/usr/lib/libsasl2.so.3.0.0
find: ‘/usr/share/polkit-1/rules.d’: Permission denied
find: ‘/usr/share/selinux/targeted/default/active’: Permission denied

```

**Comment by Jikstra** [comment]
The problem is, that deltachat-desktop is looking out for a `libsasl2.so.2` but there's only a `libsasl2.so.3`. You can just create a symlink to it. This should be possible with `cd /usr/lib && ln -s libsasl2.so.3 libsasl2.so.2`. You need to be root to do that.

**Comment by jmliz** [comment]
I created the symlink with your instructions but the exact same error appears. I also made the same thing but in the lib64 dir but still the same.

**Comment by jmliz** [comment]
here

```
lrwxrwxrwx.   1 root root       17 Jul 13  2018 libsasl2.so.3 -> libsasl2.so.3.0.0
-rwxr-xr-x.   1 root root   136376 Jul 13  2018 libsasl2.so.3.0.0
drwxr-xr-x.   2 root root     4096 Dec 21 15:01 sasl2
```

**Comment by Jikstra** [comment]
Aaah I see why it failed. There's no `libsasl2.so.3` only a `libsasl2.so.3.0.0`. Try again with `cd /usr/lib && ln -s libsasl2.so.3.0.0 libsasl2.so.2`.

You need to have a line in the `ls -al /usr/lib | grep sasl` output where you have a `... libsasl2.so.2 -> libsasl2.so.3.0.0`  line.

**Comment by flub** [comment]
You shouldn't just symlink to another name though. The whole reason the
name changed is because it is no longer ABI compatible (even though you do
stand a chance of getting lucky, you'll likely break things subtly sometime
when the cause is no longer obvious, resulting in more weirdness no one can
figure out).

You should install the new library instead.

**Comment by Jikstra** [comment]
>  You should install the new library instead.

It needs the older version which is a bit harder to get without compiling on your own i think. I tried it for some time and it seems to work with the symlink. But it's definetly a hack.

**Comment by flub** [comment]
On Sat 02 Feb 2019 at 09:11 -0800, Jikstra wrote:

>>  You should install the new library instead.
>
> It needs the older version which is a bit harder to get without
> compiling on your own i think. I tried it for some time and it seems
> to work with the symlink. But it's definetly a hack. 

I missed that is was a downgrade, but it does stay the same however.
Symlinking different soversions together is not a good thing.  Especially
if done in /usr/ rather that /usr/local since the latter is actually
where one expects local modifications.

Yes, it's all a giant pain and comes with many pitfalls and ancient
knowledge to do it all correctly in ways that won't subtly break your
systems.  I'm sorry but I'll probably never talk approvingly of taking
hackish shortcuts as it's just hurt too often in the past.  It's even
worse if you need an older release but here's what you should do in
theory:

- Get the right version of libetpan source.
  - you'll need all it's dependencies, hopefully they're on the system
    already.
- Compile it using `make`
  - Do not use `make install` since that will install header files etc of
    an older libetpan version than your system, meaning that new things
    compiled will try to build against this old one which is likely not
    what you want.  Instead do:
- Install the libetpan2.so.2.y.z library into /usr/local/lib/
  - you may need to hunt for this in libtool's .libs/ directories or so.
- Make the /usr/local/lib/libetpan2.so.2 synlink point to it

**Comment by jmliz** [comment]
even with symlnks it doesn't work

```
[user@pc lib]$ sudo ln -s libsasl2.so.3.0.0 libsasl2.so.2
[user@pc lib]$ ls -al /usr/lib | grep sasl
lrwxrwxrwx.   1 root root       17 Feb  2 22:09 libsasl2.so.2 -> libsasl2.so.3.0.0
lrwxrwxrwx.   1 root root       17 Jul 13  2018 libsasl2.so.3 -> libsasl2.so.3.0.0
-rwxr-xr-x.   1 root root   136376 Jul 13  2018 libsasl2.so.3.0.0
drwxr-xr-x.   2 root root     4096 Dec 21 15:01 sasl2
[user@pc lib]$ cd 
[user@pc ~]$ cd Downloads/
[user@pc Downloads]$ ./deltachat-desktop-0.100.0-x86_64.AppImage 
Logfile: /home/user/.config/DeltaChat/logs/2019-02-02T21:09:45.218Z.log
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libsasl2.so.2: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (/tmp/.mount_deltacTIlG6K/resources/app.asar/node_modules/node-gyp-build/index.js:16:10)
    at Object.<anonymous> (/tmp/.mount_deltacTIlG6K/resources/app.asar/node_modules/deltachat-node/binding.js:1:198)
^C[user@pc Downloads]$ cd /usr/lib64
[user@pc lib64]$ ls -al /usr/lib | grep sasl
lrwxrwxrwx.   1 root root       17 Feb  2 22:09 libsasl2.so.2 -> libsasl2.so.3.0.0
lrwxrwxrwx.   1 root root       17 Jul 13  2018 libsasl2.so.3 -> libsasl2.so.3.0.0
-rwxr-xr-x.   1 root root   136376 Jul 13  2018 libsasl2.so.3.0.0
drwxr-xr-x.   2 root root     4096 Dec 21 15:01 sasl2
[user@pc lib64]$ 

```

**Comment by jmliz** [comment]
I think I can wait for an official fix. thanks.
