### ISSUE TITLE
Mac needs openssl 

### ISSUE THREAD

**Issue by yaspal1983** [deltachat/deltachat-desktop#708]
Message:
Uncaught Exception:
Error: dlopen(/var/folders/7s/tvthn5sn5sqb8bd705fvk04c0000gn/T/.com.deltachat.desktop.eWg0ID, 1): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /var/folders/7s/tvthn5sn5sqb8bd705fvk04c0000gn/T/.com.deltachat.desktop.eWg0ID
  Reason: image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:18:10)
    at Object.<anonymous> (/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/binding.js:1:198)

- Platform (linux/mac/windows): macOS 10.14.4 (Beta 18E194d)

**Comment by Jikstra** [comment]
You need to install openssl with brew. This is not as easy as it should be, but currently the only way on mac.
If you have brew installed, it's as easy as `brew install openssl`.
