### ISSUE TITLE
DeltaChat crashes on 10.14.2

### ISSUE THREAD

**Issue by piratx** [deltachat/deltachat-desktop#758]
- Platform (linux/mac/windows): Mac
- Delta Chat Desktop Version: 0.102.0.2300
- Expected behavior: It should run
- Actual behavior: Crashes before launch
- Steps to reproduce the problem: Downloaded the dmg or the zip from the site and copied it to ~/Applications
- Screenshots:
- Logs:

./DeltaChat error log

Logfile: /Users/piratx/Library/Application Support/DeltaChat/logs/2019-04-11T11:01:10.428Z.log
/Users/piratx/Applications/DeltaChat.app/Contents/Resources/app.asar/src/main/index.js:28
  throw err
  ^

Error: dlopen(/var/folders/tp/1bb9mb6117zf_h_6jhr4ww_h0000gn/T/.com.deltachat.desktop.orPulb, 1): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /var/folders/tp/1bb9mb6117zf_h_6jhr4ww_h0000gn/T/.com.deltachat.desktop.orPulb
  Reason: image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (/Users/piratx/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:18:10)
    at Object.<anonymous> (/Users/piratx/Applications/DeltaChat.app/Contents/Resources/app.asar/node_modules/deltachat-node/binding.js:1:198)

**Comment by Simon-Laux** [comment]
At the moment you still have to install some dependencies with homebrew - We already work on a solution with including those dependencies. See the readme for more details.

**Comment by piratx** [comment]
Thank you @Simon-Laux I'll check it and I'll let you know. Thing is I installed it last month on two macs with drag n drop, I dont know what is happening now :)

**Comment by Jikstra** [comment]
@piratx it's also possible that openssl is at another location on this mac as it's normally. Check out if this `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib` file exists. I already work on a "self contained" deltachat-desktop dmg (so openssl is bundled with deltachat-desktop).

**Comment by piratx** [comment]
I did brew installed openssl and I think it’s working fine now :)
Thanks for this!
