### ISSUE TITLE
Can not built on Manjaro

### ISSUE THREAD

**Issue by alien2003** [deltachat/deltachat-desktop#792]
```
> electron-chromedriver@3.0.0 install /home/alien/deltachat-desktop-git/src/deltachat-desktop-git/node_modules/electron-chromedriver
> node ./download-chromedriver.js


> deltachat-node@0.43.0 install /home/alien/deltachat-desktop-git/src/deltachat-desktop-git/node_modules/deltachat-node
> npm run rebuild-all


> deltachat-node@0.43.0 rebuild-all /home/alien/deltachat-desktop-git/src/deltachat-desktop-git/node_modules/deltachat-node
> npm run rebuild-core && npm run rebuild-bindings


> deltachat-node@0.43.0 rebuild-core /home/alien/deltachat-desktop-git/src/deltachat-desktop-git/node_modules/deltachat-node
> node scripts/rebuild-core.js

[140/168] Compiling C object 'src/25a6634@@deltachat@sta/dc_imex.c.o'.
../src/dc_imex.c: In function ‘dc_create_setup_code’:
../src/dc_imex.c:261:5: warning: ‘RAND_pseudo_bytes’ is deprecated [-Wdeprecated-declarations]
     RAND_pseudo_bytes((unsigned char*)&random_val, sizeof(uint16_t));
     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ossl_typ.h:19,
                 from /usr/include/openssl/rand.h:14,
                 from ../src/dc_imex.c:4:
/usr/include/openssl/rand.h:44:1: note: declared here
 DEPRECATEDIN_1_1_0(int RAND_pseudo_bytes(unsigned char *buf, int num))
 ^~~~~~~~~~~~~~~~~~
[151/168] Compiling C object 'src/25a6634@@deltachat@sta/dc_openssl.c.o'.
../src/dc_openssl.c:85:13: warning: ‘dyn_destroy_function’ defined but not used [-Wunused-function]
 static void dyn_destroy_function(struct CRYPTO_dynlock_value* l, const char* file, int line)
             ^~~~~~~~~~~~~~~~~~~~
../src/dc_openssl.c:74:13: warning: ‘dyn_lock_function’ defined but not used [-Wunused-function]
 static void dyn_lock_function(int mode, struct CRYPTO_dynlock_value* l, const char* file, int line)
             ^~~~~~~~~~~~~~~~~
../src/dc_openssl.c:63:37: warning: ‘dyn_create_function’ defined but not used [-Wunused-function]
 static struct CRYPTO_dynlock_value* dyn_create_function(const char* file, int line)
                                     ^~~~~~~~~~~~~~~~~~~
../src/dc_openssl.c:46:13: warning: ‘locking_function’ defined but not used [-Wunused-function]
 static void locking_function(int mode, int n, const char* file, int line)
             ^~~~~~~~~~~~~~~~
../src/dc_openssl.c:40:22: warning: ‘id_function’ defined but not used [-Wunused-function]
 static unsigned long id_function(void)
                      ^~~~~~~~~~~
[164/168] Compiling C object 'src/25a6634@@deltachat@sta/dc_tools.c.o'.
../src/dc_tools.c: In function ‘dc_create_id’:
../src/dc_tools.c:963:3: warning: ‘RAND_pseudo_bytes’ is deprecated [-Wdeprecated-declarations]
   RAND_pseudo_bytes((unsigned char*)&buf, sizeof(uint32_t)*3);
   ^~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ossl_typ.h:19,
                 from /usr/include/openssl/rand.h:14,
                 from ../src/dc_tools.c:8:
/usr/include/openssl/rand.h:44:1: note: declared here
 DEPRECATEDIN_1_1_0(int RAND_pseudo_bytes(unsigned char *buf, int num))
 ^~~~~~~~~~~~~~~~~~
[168/168] Linking target cmdline/delta.
make: Entering directory '/home/alien/deltachat-desktop-git/src/deltachat-desktop-git/node_modules/deltachat-node/build'
  CC(target) Release/obj.target/deltachat/src/module.o
../src/module.c:23:3: error: unknown type name ‘napi_threadsafe_function’
   napi_threadsafe_function threadsafe_event_handler;
   ^~~~~~~~~~~~~~~~~~~~~~~~
../src/module.c: In function ‘dc_event_handler’:
../src/module.c:84:9: warning: implicit declaration of function ‘napi_call_threadsafe_function’; did you mean ‘napi_create_function’? [-Wimplicit-function-declaration]
         napi_call_threadsafe_function(dcn_context->threadsafe_event_handler, dcn_event, napi_tsfn_blocking);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         napi_create_function
../src/module.c:84:89: error: ‘napi_tsfn_blocking’ undeclared (first use in this function); did you mean ‘napi_closing’?
         napi_call_threadsafe_function(dcn_context->threadsafe_event_handler, dcn_event, napi_tsfn_blocking);
                                                                                         ^~~~~~~~~~~~~~~~~~
                                                                                         napi_closing
../src/module.c:84:89: note: each undeclared identifier is reported only once for each function it appears in
../src/module.c: In function ‘imap_thread_func’:
../src/module.c:159:3: warning: implicit declaration of function ‘napi_acquire_threadsafe_function’; did you mean ‘napi_create_function’? [-Wimplicit-function-declaration]
   napi_acquire_threadsafe_function(dcn_context->threadsafe_event_handler);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   napi_create_function
../src/module.c:167:3: warning: implicit declaration of function ‘napi_release_threadsafe_function’; did you mean ‘napi_create_function’? [-Wimplicit-function-declaration]
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   napi_create_function
../src/module.c:167:75: error: ‘napi_tsfn_release’ undeclared (first use in this function); did you mean ‘napi_is_date’?
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
                                                                           napi_is_date
../src/module.c: In function ‘smtp_thread_func’:
../src/module.c:182:75: error: ‘napi_tsfn_release’ undeclared (first use in this function); did you mean ‘napi_is_date’?
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
                                                                           napi_is_date
../src/module.c: In function ‘mvbox_thread_func’:
../src/module.c:198:75: error: ‘napi_tsfn_release’ undeclared (first use in this function); did you mean ‘napi_is_date’?
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
                                                                           napi_is_date
../src/module.c: In function ‘sentbox_thread_func’:
../src/module.c:213:75: error: ‘napi_tsfn_release’ undeclared (first use in this function); did you mean ‘napi_is_date’?
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
                                                                           napi_is_date
../src/module.c: In function ‘dcn_context_new’:
../src/module.c:319:41: warning: assignment to ‘int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
   dcn_context->threadsafe_event_handler = NULL;
                                         ^
In file included from ../src/napi-macros-extensions.h:1,
                 from ../src/module.c:10:
../src/module.c: In function ‘dcn_set_event_handler’:
../src/module.c:1288:22: warning: implicit declaration of function ‘napi_create_threadsafe_function’; did you mean ‘napi_create_function’? [-Wimplicit-function-declaration]
   NAPI_STATUS_THROWS(napi_create_threadsafe_function(
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../napi-macros/napi-macros.h:21:8: note: in definition of macro ‘NAPI_STATUS_THROWS’
   if ((call) != napi_ok) { \
        ^~~~
../src/module.c: In function ‘dcn_unset_event_handler’:
../src/module.c:1402:75: error: ‘napi_tsfn_release’ undeclared (first use in this function); did you mean ‘napi_is_date’?
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
                                                                           napi_is_date
make: *** [deltachat.target.mk:106: Release/obj.target/deltachat/src/module.o] Error 1
make: Leaving directory '/home/alien/deltachat-desktop-git/src/deltachat-desktop-git/node_modules/deltachat-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.19.36-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alien/deltachat-desktop-git/src/deltachat-desktop-git/node_modules/deltachat-node
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npx failed with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-node@0.43.0 rebuild-core: `node scripts/rebuild-core.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-node@0.43.0 rebuild-core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alien/.npm/_logs/2019-05-14T08_07_59_506Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-node@0.43.0 rebuild-all: `npm run rebuild-core && npm run rebuild-bindings`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-node@0.43.0 rebuild-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alien/.npm/_logs/2019-05-14T08_07_59_520Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-node@0.43.0 install: `npm run rebuild-all`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-node@0.43.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alien/.npm/_logs/2019-05-14T08_08_00_669Z-debug.log

```

Manjaro x64
deltachat git package from AUR

**Comment by ralphtheninja** [comment]
You need to use node 10, we don't support 11 or 12 yet.

**Comment by Jikstra** [comment]
support for node 11 and 12 is in latest deltachat-node v0.44.0 but it's not used in desktop yet. Maybe a npm update pulls it in, which could (?) fix this issue. v0.44.0 just got released a couple of hours ago :)

**Comment by alien2003** [comment]
@ralphtheninja @Jikstra thank you. I gues PKGBUILD should be rewrited to force old node version

**Comment by Jikstra** [comment]
@alien2003 yup and we definetly should add some docker tests for the PKGBUILD, currently i'm only testing it on my dev machine :/
