### ISSUE TITLE
Unable to login (Login button greyed out)

### ISSUE THREAD

**Issue by severin-lemaignan** [deltachat/deltachat-desktop#819]
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: 0.102.0-PREVIEW (installed from flathub)
- Expected behavior: On the login screen, click on 'Advanced', fill in all the field, press Login to login 
- Actual behavior: Unable to login, as the login button remains greyed out, without providing information regarding missing/incomplete/invalid fields (as far as I can tell, all the fields are filled in)
- Steps to reproduce the problem: Launch delta.chat and try to log in

- Logs:
```
"2019-05-27T19:14:04.163Z"	"main/index"	"INFO"	[]	"cwd /home/skadge/.var/app/chat.delta.desktop/config/DeltaChat"
"2019-05-27T19:14:04.220Z"	"main/menu"	"INFO"	[]	"rebuilding menu with locale en"
"2019-05-27T19:14:06.245Z"	"main/state"	"INFO"	[]	"Saving state to /home/skadge/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
"2019-05-27T19:14:07.431Z"	"main/state"	"INFO"	[]	"Saving state to /home/skadge/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
"2019-05-27T19:14:32.004Z"	"main/deltachat"	"INFO"	[]	"Using deltachat instance /home/skadge/.var/app/chat.delta.desktop/config/DeltaChat/7365766572696e406775616b616d6f6c652e6f7267"
"2019-05-27T19:14:33.825Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":120,"fileName":"/app/delta/resources/app.asar/src/main/deltachat.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/app/delta/resources/app.asar/src/main/deltachat.js:120:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":697,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"handleEvent","source":"    at handleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:697:12)"},{"columnNumber":13,"lineNumber":572,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"Timeout._pollInterval.setInterval [as _onTimeout]","source":"    at Timeout._pollInterval.setInterval [as _onTimeout] (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:572:13)"},{"columnNumber":11,"lineNumber":425,"fileName":"timers.js","functionName":"ontimeout","source":"    at ontimeout (timers.js:425:11)"},{"columnNumber":5,"lineNumber":289,"fileName":"timers.js","functionName":"tryOnTimeout","source":"    at tryOnTimeout (timers.js:289:5)"},{"columnNumber":5,"lineNumber":252,"fileName":"timers.js","functionName":"listOnTimeout","source":"    at listOnTimeout (timers.js:252:5)"},{"columnNumber":10,"lineNumber":212,"fileName":"timers.js","functionName":"Timer.processTimers","source":"    at Timer.processTimers (timers.js:212:10)"}]	"Not configured, cannot connect."
"2019-05-27T19:14:33.925Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":120,"fileName":"/app/delta/resources/app.asar/src/main/deltachat.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/app/delta/resources/app.asar/src/main/deltachat.js:120:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":697,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"handleEvent","source":"    at handleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:697:12)"},{"columnNumber":13,"lineNumber":572,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"Timeout._pollInterval.setInterval [as _onTimeout]","source":"    at Timeout._pollInterval.setInterval [as _onTimeout] (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:572:13)"},{"columnNumber":11,"lineNumber":425,"fileName":"timers.js","functionName":"ontimeout","source":"    at ontimeout (timers.js:425:11)"},{"columnNumber":5,"lineNumber":289,"fileName":"timers.js","functionName":"tryOnTimeout","source":"    at tryOnTimeout (timers.js:289:5)"},{"columnNumber":5,"lineNumber":252,"fileName":"timers.js","functionName":"listOnTimeout","source":"    at listOnTimeout (timers.js:252:5)"},{"columnNumber":10,"lineNumber":212,"fileName":"timers.js","functionName":"Timer.processTimers","source":"    at Timer.processTimers (timers.js:212:10)"}]	"Not configured, cannot connect."
"2019-05-27T19:14:34.126Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":120,"fileName":"/app/delta/resources/app.asar/src/main/deltachat.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/app/delta/resources/app.asar/src/main/deltachat.js:120:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":697,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"handleEvent","source":"    at handleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:697:12)"},{"columnNumber":13,"lineNumber":572,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"Timeout._pollInterval.setInterval [as _onTimeout]","source":"    at Timeout._pollInterval.setInterval [as _onTimeout] (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:572:13)"},{"columnNumber":11,"lineNumber":425,"fileName":"timers.js","functionName":"ontimeout","source":"    at ontimeout (timers.js:425:11)"},{"columnNumber":5,"lineNumber":289,"fileName":"timers.js","functionName":"tryOnTimeout","source":"    at tryOnTimeout (timers.js:289:5)"},{"columnNumber":5,"lineNumber":252,"fileName":"timers.js","functionName":"listOnTimeout","source":"    at listOnTimeout (timers.js:252:5)"},{"columnNumber":10,"lineNumber":212,"fileName":"timers.js","functionName":"Timer.processTimers","source":"    at Timer.processTimers (timers.js:212:10)"}]	"Not configured, cannot connect."
"2019-05-27T19:14:34.176Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":120,"fileName":"/app/delta/resources/app.asar/src/main/deltachat.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/app/delta/resources/app.asar/src/main/deltachat.js:120:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":697,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"handleEvent","source":"    at handleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:697:12)"},{"columnNumber":13,"lineNumber":572,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"Timeout._pollInterval.setInterval [as _onTimeout]","source":"    at Timeout._pollInterval.setInterval [as _onTimeout] (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:572:13)"},{"columnNumber":11,"lineNumber":425,"fileName":"timers.js","functionName":"ontimeout","source":"    at ontimeout (timers.js:425:11)"},{"columnNumber":5,"lineNumber":289,"fileName":"timers.js","functionName":"tryOnTimeout","source":"    at tryOnTimeout (timers.js:289:5)"},{"columnNumber":5,"lineNumber":252,"fileName":"timers.js","functionName":"listOnTimeout","source":"    at listOnTimeout (timers.js:252:5)"},{"columnNumber":10,"lineNumber":212,"fileName":"timers.js","functionName":"Timer.processTimers","source":"    at Timer.processTimers (timers.js:212:10)"}]	"Not configured, cannot connect."
"2019-05-27T19:14:34.226Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":120,"fileName":"/app/delta/resources/app.asar/src/main/deltachat.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/app/delta/resources/app.asar/src/main/deltachat.js:120:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":697,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"handleEvent","source":"    at handleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:697:12)"},{"columnNumber":13,"lineNumber":572,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"Timeout._pollInterval.setInterval [as _onTimeout]","source":"    at Timeout._pollInterval.setInterval [as _onTimeout] (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:572:13)"},{"columnNumber":11,"lineNumber":425,"fileName":"timers.js","functionName":"ontimeout","source":"    at ontimeout (timers.js:425:11)"},{"columnNumber":5,"lineNumber":289,"fileName":"timers.js","functionName":"tryOnTimeout","source":"    at tryOnTimeout (timers.js:289:5)"},{"columnNumber":5,"lineNumber":252,"fileName":"timers.js","functionName":"listOnTimeout","source":"    at listOnTimeout (timers.js:252:5)"},{"columnNumber":10,"lineNumber":212,"fileName":"timers.js","functionName":"Timer.processTimers","source":"    at Timer.processTimers (timers.js:212:10)"}]	"Not configured, cannot connect."
"2019-05-27T19:14:34.377Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":120,"fileName":"/app/delta/resources/app.asar/src/main/deltachat.js","functionName":"DeltaChat.dc.on","source":"    at DeltaChat.dc.on (/app/delta/resources/app.asar/src/main/deltachat.js:120:11)"},{"columnNumber":13,"lineNumber":182,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:182:13)"},{"columnNumber":12,"lineNumber":697,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"handleEvent","source":"    at handleEvent (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:697:12)"},{"columnNumber":13,"lineNumber":572,"fileName":"/app/delta/resources/app.asar/node_modules/deltachat-node/index.js","functionName":"Timeout._pollInterval.setInterval [as _onTimeout]","source":"    at Timeout._pollInterval.setInterval [as _onTimeout] (/app/delta/resources/app.asar/node_modules/deltachat-node/index.js:572:13)"},{"columnNumber":11,"lineNumber":425,"fileName":"timers.js","functionName":"ontimeout","source":"    at ontimeout (timers.js:425:11)"},{"columnNumber":5,"lineNumber":289,"fileName":"timers.js","functionName":"tryOnTimeout","source":"    at tryOnTimeout (timers.js:289:5)"},{"columnNumber":5,"lineNumber":252,"fileName":"timers.js","functionName":"listOnTimeout","source":"    at listOnTimeout (timers.js:252:5)"},{"columnNumber":10,"lineNumber":212,"fileName":"timers.js","functionName":"Timer.processTimers","source":"    at Timer.processTimers (timers.js:212:10)"}]	"Not configured, cannot connect."
```

**Comment by Jikstra** [comment]
Have you filled out the e-mail & password fields? It's possible that even if you have filled out advanced config, you still need them two. If this is not the case, can you provide information on which fields you have filled out and which not?

**Comment by severin-lemaignan** [comment]
Trying again today, the login button was not greyed out anymore, and I could login. ...not sure why I had the error the first time (as I'm rather certain that all the fields were filled up). Anyway, closing the issue for now.
