### ISSUE TITLE
Login not working with newest dc-node

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#841]
"Make options in bindings 1-1 with options in core " breaks compatibility with desktop. I propose a major increase of the version number, cause it breaks api.
```
main/index ERROR [ { columnNumber: 7,
    lineNumber: 27,
    fileName:
     '/home/simon/Documents/Projects/deltachat-desktop/deltachat-desktop/src/main/index.js',
    functionName: 'process.on',
    source:
     '    at process.on (/home/simon/Documents/Projects/deltachat-desktop/deltachat-desktop/src/main/index.js:27:7)' },
  { columnNumber: 15,
    lineNumber: 187,
    fileName: 'events.js',
    functionName: 'process.emit',
    source: '    at process.emit (events.js:187:15)' },
  { columnNumber: 27,
    lineNumber: 488,
    fileName: 'internal/bootstrap/node.js',
    functionName: 'process._fatalException',
    source:
     '    at process._fatalException (internal/bootstrap/node.js:488:27)' } ] uncaughtError { message: 'Missing .mail_pw',
  stack:
   'Error: Missing .mail_pw\n    at DeltaChat.configure (/home/simon/Documents/Projects/deltachat-node/lib/deltachat.js:107:13)\n    at dc.open.err (/home/simon/Documents/Projects/deltachat-desktop/deltachat-desktop/src/main/deltachat/login.js:45:10)\n    at binding.dcn_open.err (/home/simon/Documents/Projects/deltachat-node/lib/deltachat.js:579:9)' }
/home/simon/Documents/Projects/deltachat-desktop/deltachat-desktop/src/main/index.js:28
  throw err
  ^

Error: Missing .mail_pw
    at DeltaChat.configure (/home/simon/Documents/Projects/deltachat-node/lib/deltachat.js:107:13)
    at dc.open.err (/home/simon/Documents/Projects/deltachat-desktop/deltachat-desktop/src/main/deltachat/login.js:45:10)
    at binding.dcn_open.err (/home/simon/Documents/Projects/deltachat-node/lib/deltachat.js:579:9)
```

**Comment by Jikstra** [comment]
Newest dc-node is which version?

**Comment by ralphtheninja** [comment]
There isn't any newest version. I just made a test version.

@Simon-Laux We will bump the version to a new major as you suggested. It's a good idea!
