### ISSUE TITLE
npm run dist fails on windows

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-desktop#871]
node version: v12.4.0

Starts and works correctly, but electron builder fails :/

@ralphtheninja @Simon-Laux can you reproduce this?

```
C:\Users\bb\opensource\deltachat-desktop>npm run dist
 
> deltachat-desktop@0.104.0 dist C:\Users\bb\opensource\deltachat-desktop
> electron-builder --publish=onTagOrDraft
 
  • electron-builder version=20.43.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist\builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=4.2.4 appOutDir=dist\win-unpacked
  ⨯ image: unknown format
github.com/develar/go-fs-util.CloseAndCheckError
        /Volumes/data/go/pkg/mod/github.com/develar/go-fs-util@v2.0.1-0.20181113101504-f6630ccc0e93+incompatible/fs.go:120
github.com/develar/app-builder/pkg/icons.DecodeImageAndClose
        /Volumes/data/Documents/app-builder/pkg/icons/image-util.go:90
github.com/develar/app-builder/pkg/icons.LoadImage
        /Volumes/data/Documents/app-builder/pkg/icons/image-util.go:54
github.com/develar/app-builder/pkg/icons.loadImage
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:346
github.com/develar/app-builder/pkg/icons.configureInputInfoFromSingleFile
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:328
github.com/develar/app-builder/pkg/icons.doConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:244
github.com/develar/app-builder/pkg/icons.ConvertIcon
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
        /Volumes/data/Documents/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:80
runtime.main
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/proc.go:200
runtime.goexit
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337
 
Error: C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.<anonymous> (C:\Users\bb\opensource\deltachat-desktop\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:288:20)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
From previous event:
    at WinPackager.resolveIcon (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\platformPackager.ts:594:101)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\platformPackager.ts:573:31
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.getOrConvertIcon (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\platformPackager.ts:572:54)
    at Lazy.<anonymous> (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\winPackager.ts:79:43)
    at Lazy.get value [as value] (C:\Users\bb\opensource\deltachat-desktop\node_modules\lazy-val\src\main.ts:18:25)
    at WinPackager.getIconPath (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\winPackager.ts:190:27)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\winPackager.ts:287:33
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signAndEditResources (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\winPackager.ts:260:158)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\winPackager.ts:363:21
    at go$readdir$cb (C:\Users\bb\opensource\deltachat-desktop\node_modules\graceful-fs\graceful-fs.js:162:14)
    at FSReqCallback.oncomplete (fs.js:153:23)
From previous event:
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\winPackager.ts:355:73)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at WinPackager.doPack (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:166:5)
From previous event:
    at Packager.doBuild (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:153:23)
From previous event:
    at Packager._build (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Packager.build (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Users\bb\opensource\deltachat-desktop\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Users\bb\opensource\deltachat-desktop\node_modules\electron-builder\src\builder.ts:228:10)
    at C:\Users\bb\opensource\deltachat-desktop\node_modules\electron-builder\src\cli\cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-desktop@0.104.0 dist: `electron-builder --publish=onTagOrDraft`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deltachat-desktop@0.104.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bb\AppData\Roaming\npm-cache\_logs\2019-06-25T15_16_56_511Z-debug.log
```

**Comment by ralphtheninja** [comment]
@Jikstra I'll try to check later if I remember it.
