### ISSUE TITLE
SMTP failed to send message: 5.7.0 authentication failed

### ISSUE THREAD

**Issue by simonsan** [deltachat/deltachat-desktop#959]
- Platform (linux/mac/windows): Windows 10 v1903
- Delta Chat Desktop Version: Version 0.105.0-pre1-PREVIEW
- Expected behavior: Messages getting send
- Actual behavior: Messages don't get sent due to SMTP auth error
- Steps to reproduce the problem: Send a message
- Message info: `State: Pending, Encrypted`

- Logs:
```
"2019-08-31T12:52:53.624Z"	"main/deltachat"	"WARNING"	[{"columnNumber":11,"lineNumber":145,"fileName":"C:\\Users\\<username>\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\index.js","functionName":"DeltaChat.<anonymous>","source":"    at DeltaChat.<anonymous> (C:\\Users\\<username>\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\index.js:145:11)"},{"columnNumber":13,"lineNumber":194,"fileName":"events.js","functionName":"DeltaChat.emit","source":"    at DeltaChat.emit (events.js:194:13)"},{"columnNumber":12,"lineNumber":738,"fileName":"C:\\Users\\<username>\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js","functionName":"handleEvent","source":"    at handleEvent (C:\\Users\\<username>\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:738:12)"},{"columnNumber":7,"lineNumber":35,"fileName":"C:\\Users\\<username>\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js","source":"    at C:\\Users\\<username>\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7"}]	"SMTP failed to send message: 5.7.0 authentication failed"
```

- JSON:
```
{
    "arch": "64",
    "blobdir": "C:\\Users\\<username>\\AppData\\Local\\DeltaChat\\<xxx>\\db.sqlite-blobs",
    "configured_mvbox_folder": "DeltaChat",
    "configured_sentbox_folder": "Sent",
    "database_dir": "C:\\Users\\<username>\\AppData\\Local\\DeltaChat\\<xxx>\\db.sqlite",
    "database_version": "55",
    "deltachat_core_version": "v1.0.0-alpha.1",
    "display_name": "0",
    "e2ee_enabled": "1",
    "entered_account_settings": "<email> <username>:***:imap.<domain>.<tld>:993 mail.<domain>.<tld>:***:mail.<domain>.<tld>:465 0",
    "fingerprint": "xxx",
    "folders_configured": "3",
    "inbox_watch": "1",
    "is_configured": "1",
    "level": "awesome",
    "mdns_enabled": "1",
    "messages_in_contact_requests": "0",
    "mvbox_move": "1",
    "mvbox_watch": "1",
    "number_of_chat_messages": "103",
    "number_of_chats": "2",
    "number_of_contacts": "2",
    "private_key_count": "2",
    "public_key_count": "2",
    "sentbox_watch": "1",
    "sqlite_thread_safe": "1",
    "sqlite_version": "3.27.2",
    "used_account_settings": "<email> <username>:***:imap.<domain>.<tld>:993 mail.<domain>.<tld>:***:mail.<domain>.<tld>:465 AUTH_NORMAL IMAP_SSL SMTP_SSL "
}

**Comment by Jikstra** [comment]
0.105 is a pre release and uses a different version of the core library which is fastly changing (it's a port from c to rust). Can you give this a try with 0.104.0? Probably it's a bug that's already fixed. What email provider do you use?

**Comment by simonsan** [comment]
> 0.105 is a pre release and uses a different version of the core library which is fastly changing (it's a port from c to rust). Can you give this a try with 0.104.0? Probably it's a bug that's already fixed. What email provider do you use?
> Thanks for reporting :)

I also see now that I run `pre2`, I think it is not (automatically) changed in the `About DeltaChat` window. Personally I would prefer to wait for another pre-release as I was intentionally downloading the version based on the rust-core lib. My Emailprovider is `in-berlin.de`, here you can find the [login details](http://wiki.in-berlin.de/zugangsdaten) if in need.

**Comment by Jikstra** [comment]
pre2 is very buggy and also the other pre releases are. The best experience (but changing everyday) is setting up a full dev environment, pull latest rust core, latest -node bindings and latest desktop. This works wellish currently. I'm currently working on a big pr, maybe i should release a new pre release before merging this (with latest rust core of course).

**Comment by simonsan** [comment]
No need to rush anything ;-) Glad y'all doing it.

**Comment by Jikstra** [comment]
Just rechecked your config with what they write in their wiki and deltachat should work with it. So i guess it's a rust core problem which maybe is already fixed.

**Comment by Jikstra** [comment]
Closing for now, if this still happens with current rust core, please reopen :)

**Comment by simonsan** [comment]
Same :-( 

`"2019-09-27T13:36:23.397Z"  "main/deltachat"    "WARNING"   "\nDeltaChat.dc.on()@C:\\Users\\<username>\\Desktop\\win-unpacked\\resources\\app.asar\\src\\main\\deltachat\\index.js:119:11,\nDeltaChat.emit()@events.js:182:13,\nhandleEvent()@C:\\Users\\<username>\\Desktop\\win-unpacked\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:738:12,\nDeltaChat.binding.dcn_set_event_handler()@C:\\Users\\<username>\\Desktop\\win-unpacked\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7" "SMTP failed to send message: 5.7.0 authentication failed"`

**Comment by simonsan** [comment]
Please reopen. @Jikstra

**Comment by Jikstra** [comment]
Oh always thought humans can reopen their issues. Nevermind. We can't really do a lot on this on desktop side, as the rust core completely handels the connection. Will create a issue for this on the deltachat-core-rust repo.
