### ISSUE TITLE
Build fails on debian/oldstable

### ISSUE THREAD

**Issue by cehteh** [deltachat/deltachat-desktop#979]
- Platform (linux/mac/windows):
 $ cat /etc/debian_version ; uname -a
 9.11
 Linux wolke 5.2.11ct #54 SMP PREEMPT Sun Sep 1 20:50:04 CEST 2019 x86_64 GNU/Linux
- Delta Chat Desktop Version:
 deltachat-desktop$ git describe --tags --dirty --always
 v0.105.0-pre2-296-gc568ff3
- Expected behavior:
 It Builds
- Actual behavior:
 Build fails with error as seen below
- Steps to reproduce the problem:
 git pull; npm i
- Screenshots:
- Logs:
```
 Finished release [optimized] target(s) in 3m 18s
make: Entering directory '/home/ct/src/other/deltachat-desktop/node_modules/deltachat-node/build'
  CC(target) Release/obj.target/deltachat/src/module.o
../src/module.c:29:3: error: unknown type name 'napi_threadsafe_function'
   napi_threadsafe_function threadsafe_event_handler;
   ^~~~~~~~~~~~~~~~~~~~~~~~
../src/module.c: In function 'dc_event_handler':
../src/module.c:85:24: warning: implicit declaration of function 'napi_call_threadsafe_function' [-Wimplicit-function-declaration]
   napi_status status = napi_call_threadsafe_function(dcn_context->threadsafe_event_handler, dcn_event, napi_tsfn_nonblocking);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/module.c:85:104: error: 'napi_tsfn_nonblocking' undeclared (first use in this function)
   napi_status status = napi_call_threadsafe_function(dcn_context->threadsafe_event_handler, dcn_event, napi_tsfn_nonblocking);
                                                                                                        ^~~~~~~~~~~~~~~~~~~~~
../src/module.c:85:104: note: each undeclared identifier is reported only once for each function it appears in
../src/module.c:87:17: error: 'napi_queue_full' undeclared (first use in this function)
   if (status == napi_queue_full) {
                 ^~~~~~~~~~~~~~~
../src/module.c: In function 'imap_thread_func':
../src/module.c:165:3: warning: implicit declaration of function 'napi_acquire_threadsafe_function' [-Wimplicit-function-declaration]
   napi_acquire_threadsafe_function(dcn_context->threadsafe_event_handler);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/module.c:175:3: warning: implicit declaration of function 'napi_release_threadsafe_function' [-Wimplicit-function-declaration]
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/module.c:175:75: error: 'napi_tsfn_release' undeclared (first use in this function)
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
../src/module.c: In function 'smtp_thread_func':
../src/module.c:192:75: error: 'napi_tsfn_release' undeclared (first use in this function)
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
../src/module.c: In function 'mvbox_thread_func':
../src/module.c:210:75: error: 'napi_tsfn_release' undeclared (first use in this function)
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
../src/module.c: In function 'sentbox_thread_func':
../src/module.c:227:75: error: 'napi_tsfn_release' undeclared (first use in this function)
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
../src/module.c: In function 'dcn_context_new':
../src/module.c:327:41: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
   dcn_context->threadsafe_event_handler = NULL;
                                         ^
../src/module.c: In function 'dcn_close_execute':
../src/module.c:467:77: error: 'napi_tsfn_release' undeclared (first use in this function)
     napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                             ^~~~~~~~~~~~~~~~~
../src/module.c:503:43: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
     dcn_context->threadsafe_event_handler = NULL;
                                           ^
In file included from ../src/napi-macros-extensions.h:1:0,
                 from ../src/module.c:10:
../src/module.c: In function 'dcn_set_event_handler':
../src/module.c:1525:22: warning: implicit declaration of function 'napi_create_threadsafe_function' [-Wimplicit-function-declaration]
   NAPI_STATUS_THROWS(napi_create_threadsafe_function(
                      ^
../../napi-macros/napi-macros.h:21:8: note: in definition of macro 'NAPI_STATUS_THROWS'
   if ((call) != napi_ok) { \
        ^~~~
deltachat.target.mk:106: recipe for target 'Release/obj.target/deltachat/src/module.o' failed
make: *** [Release/obj.target/deltachat/src/module.o] Error 1
make: Leaving directory '/home/ct/src/other/deltachat-desktop/node_modules/deltachat-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ct/src/other/deltachat-desktop/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.2.11ct
gyp ERR! command "/usr/bin/node" "/home/ct/src/other/deltachat-desktop/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ct/src/other/deltachat-desktop/node_modules/deltachat-node
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-node@1.0.0-alpha.5 node-gyp-build: `node-gyp-build "node scripts/rebuild-core.js" "node scripts/postinstall.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-node@1.0.0-alpha.5 node-gyp-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ct/.npm/_logs/2019-09-11T13_09_19_743Z-debug.log
npm failed with code 1
npm WARN deltachat-desktop@0.105.0-pre2 license should be a valid SPDX license expression
npm WARN The package tempy is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-node@1.0.0-alpha.5 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-node@1.0.0-alpha.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ct/.npm/_logs/2019-09-11T13_09_22_663Z-debug.log
```

**Comment by Jikstra** [comment]
What node version do you use? You need to have napi support which is a more new feature. You also need to have the napi headers available.

**Comment by cehteh** [comment]
Whatever debian installed:
```
$ npm --version
5.8.0
```

I don't even know what 'napi' is, I just wanted to report that building on debian/oldstable fails. For what its worth maybe that's just ok and not supported anymore.

**Comment by nicodh** [comment]
@Jikstra  can we do some checks before running the install scripts and give meaningful error messages if some dependencies are missing?
